Best support vector tiles
iTowns/itowns pull request #1250
Opened 2019-10-30 14:47 UTC by gchoqueux

## Description
Add supports to
 * layers ordering
 * pattern
 * fill stroke
 * line cap and join
 * dash line
 * multi styles
 * styles by zoom level

and some fixes.

![vt](https://user-images.githubusercontent.com/11291849/67868583-7a453700-fb2c-11e9-8ac2-576fad8e711c.png)

2019-10-30 16:23 UTC, zarov requested changes
Nice to have those improvements !

2019-10-30 16:23 UTC, zarov commented on src/Source/Source.js
> +        return supportedParsers.get(this.format) !== undefined;
This could be a value set in the constructor, as it doesn't seem to change.

2019-10-30 16:23 UTC, zarov commented on src/Core/Feature.js
> +        if (feature && this.optionsFeature.mergeFeatures) {
If I understand correctly, simply having `feature` is not sufficient and will return a new one ? Why ?

2019-10-30 16:23 UTC, zarov commented on src/Core/Feature.js
> +    getReference(feature) {
Could you add a little comment/documentation on what is this method supposed to return ? It seems that it is a `clone`, so maybe do a `Feature#clone` method instead ?

2019-10-30 16:23 UTC, zarov commented on src/Core/Style.js
> +                const ctx = c.getContext('2d');
Could you instance a canvas globally, so you don't have to get the context everytime ?

2019-10-30 16:23 UTC, zarov commented on src/Parser/VectorTileParser.js
> +            const layerStyle = layerStyles.filter(l => (!l.minzoom || l.minzoom <= z) && (!l.maxzoom || l.maxzoom >= z));
Why not apply all conditions to the filter the first time ?

2019-10-31 09:43 UTC, gchoqueux commented on src/Core/Feature.js
> +        if (feature && this.optionsFeature.mergeFeatures) {
yes

2019-10-31 09:43 UTC, gchoqueux commented on src/Source/Source.js
> +        return supportedParsers.get(this.format) !== undefined;
yes

2019-10-31 09:48 UTC, gchoqueux commented on src/Core/Feature.js
> +        if (feature && this.optionsFeature.mergeFeatures) {
For rendering, Vector tiles layers need to be ordered. If layers are grouped by type, it's more complicated to order. So, for vector tiles I add a feature by layer.

2019-10-31 10:12 UTC, gchoqueux commented on src/Core/Feature.js
> +    getReference(feature) {
I added a documentation

2019-10-31 10:13 UTC, gchoqueux commented on src/Core/Style.js
> +                const ctx = c.getContext('2d');
I'll try

2019-10-31 16:06 UTC, gchoqueux commented on src/Parser/VectorTileParser.js
> +            const layerStyle = layerStyles.filter(l => (!l.minzoom || l.minzoom <= z) && (!l.maxzoom || l.maxzoom >= z));
yes

2019-11-04 13:40 UTC, gchoqueux commented
@zarov PR updated

2019-11-05 09:31 UTC, zarov commented on src/Source/Source.js
> +        this.isVectorSource = source.parser || supportedParsers.get(source.format);
This isn't a boolean. It might works for some case, but it's better to set a boolean.

2019-11-05 09:31 UTC, zarov commented on src/Core/Feature.js
> +        if (feature && this.optionsFeature.mergeFeatures) {
It should return the `feature` if it is found, if `mergeFeatures` is not defined, so you get something like this:
```js
if (feature && (this.optionsFeature.mergeFeatures == undefined || this.optionsFeature.mergeFeatures)) {
```
or else you should rename the function as it does not really get the Feature but only the Feature if the Features are merged.

2019-11-05 10:02 UTC, zarov commented on examples/js/plugins/FeatureToolTip.js
> +            style = (layer.style && layer.style.isStyle) ? layer.style : (feature.geometry._feature.style || geometry.properties.style);
Can be `geometry._feature.style`

2019-11-05 13:48 UTC, zarov approved these changes
LGTM, thanks for these improvements !

2019-11-05 13:49 UTC, merged