GlobeControls exported + dispose() method added to FirstPersonControl…
iTowns/itowns pull request #1499
Opened 2020-10-12 09:48 UTC by epaizreyes

…s and StreetControls

## Description

## Motivation and Context

## Screenshots (if appropriate)

2020-10-12 11:56 UTC, gchoqueux requested changes
Thanks, for this PR

2020-10-12 11:56 UTC, gchoqueux commented on src/Controls/FirstPersonControls.js
> +            window.addEventListener('keyup', this._onKeyUp, false);
You could keep **`document`** instead of **`window`**.

2020-10-12 11:56 UTC, gchoqueux commented on src/Controls/FirstPersonControls.js
> +            window.removeEventListener('keyup', this._onKeyUp, false);
You could keep **`document`** instead of **`window`**.

2020-10-12 11:56 UTC, gchoqueux commented on src/Controls/FirstPersonControls.js
> +            view.domElement.addEventListener('click', this.onFocus);
you could use `this._onFocus` not `this.onFocus`

2020-10-12 11:56 UTC, gchoqueux commented on src/Controls/FirstPersonControls.js
> +            this.view.domElement.removeEventListener('click', this.onFocus);
you could use `this._onFocus` not `this.onFocus`

2020-10-12 11:56 UTC, gchoqueux commented on src/Controls/StreetControls.js
> +        this.dispatchEvent({ type: 'dispose' });
could remove `this.dispatchEvent`, it's useless because is already called in `super.dispose();`

2020-10-12 11:56 UTC, gchoqueux commented on src/Main.js
> +export { default as GlobeControls } from 'Controls/GlobeControls';
You can keep 1 commit for this pull request.
But it's better to separate by scope, the modifications in different commits.

2020-10-12 17:16 UTC, gchoqueux reviewed
Thanks, LGTM

You just have to squash and rename the commits. (with [Commit Message Format](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-format))

You could write by example in 2 commits:

* feat(controls): add dispose method in FirstPersonControls.
* chore: export GlobeControls in itowns api.

2020-10-13 08:51 UTC, epaizreyes commented
Thanks for the comments! Hope is working well now :)

2020-10-13 09:38 UTC, gchoqueux commented
Could you squash this commit

* `export GlobeControls + dispose method in FirstPersonControls and StreetControls`

in this commit:

* `feat(controls): add dispose method in FirstPersonControls and StreetControls`

and keep commit message : `feat(controls): add dispose method in FirstPersonControls and StreetControls`

2020-10-13 09:54 UTC, epaizreyes commented
> Could you squash this commit
> 
> * `export GlobeControls + dispose method in FirstPersonControls and StreetControls`
> 
> in this commit:
> 
> * `feat(controls): add dispose method in FirstPersonControls and StreetControls`
> 
> and keep commit message : `feat(controls): add dispose method in FirstPersonControls and StreetControls`

Commit is now squashed.

2020-10-13 11:58 UTC, gchoqueux commented
ok, thanks, I merge the PR

2020-10-13 11:58 UTC, gchoqueux approved these changes

2020-10-13 11:58 UTC, merged