Add class Cursor for shapes modification
iTowns/itowns pull request #1602
Opened 2021-03-03 14:32 UTC by ftoromanoff

## Description
Add a class 'Cursor' in PlanarControl for the gestion of cursor shape 

## Motivation and Context
It's helpfull when the client wants to change the default curseur (Work in progress for instance) without the state of itowns being differente than NONE

## Screenshots (if appropriate)

2021-03-03 15:04 UTC, mgermerie approved these changes

2021-03-04 09:46 UTC, gchoqueux requested changes
could you move `Cursor` method and `shape` property in `PlanarControls`?

2021-03-04 09:48 UTC, gchoqueux commented
Could you add documentation on method (to explain all states)?
Could you rename `setShape` to `setCursor`?

2021-03-04 10:38 UTC, gchoqueux approved these changes
Thanks!

2021-03-04 10:53 UTC, merged