Layer update strategies
iTowns/itowns pull request #191
Opened 2016-09-30 08:28 UTC by peppsac

Implement different (and configurable) update strategies for layer.

2016-09-30 16:01 UTC, gchoqueux requested changes

2016-09-30 16:01 UTC, gchoqueux commented on index.html
> +                updateStrategy: {
should be added default value when there's no updateStrategy

2016-09-30 16:02 UTC, gchoqueux commented
No updating/reloading when a layer going from invisible to visible

2016-09-30 16:08 UTC, nosy-b commented
Same bug as the master:
When going **outside of France** even with only 'Ortho' imagery layer activated it tries to download other layers data deactivated(ex: SCAN-EXPRESS.STANDARD)

2016-09-30 16:13 UTC, peppsac commented
> Same bug as the master:
> When going outside of France even with only 'Ortho' imagery layer activated it tries to download other layers data deactivated(ex: SCAN-EXPRESS.STANDARD)

It's expected.
To be `loaded` a tile needs to have all of its textures, regardless of the status of the layer.
So while I agree with you that this is *wrong*, a proper fix would be to rework the `child.texturesNeeded` mechanism.

Note : a tile expect to have at least 1 texture per layer where `tileInsideLimit` returns true.

2016-10-03 07:55 UTC, peppsac commented on index.html
> +                updateStrategy: {
Fixed.

2016-10-03 07:56 UTC, peppsac commented
> No updating/reloading when a layer going from invisible to visible

Fixed as well (calling `update()` instead of `scene.renderScene3D()` in `ApiGlobe.prototype.setLayerVisibility`)

2016-10-03 14:14 UTC, merged

2016-10-03 14:14 UTC, gchoqueux commented
r+