In this PR :
iTowns/itowns pull request #193
Opened 2016-10-10 09:14 UTC by vcoindet

All changes are in ApiGlobe.js.

1 - ApiGlobe.prototype.addEventListener = function (eventname, callback){

    this.viewerDiv.addEventListener(eventname, callback, false);

};

2 - Adding the following Events :
centerchanged 
zoomchanged
orientationchanged
layerchanged In Progress
layerchanged:visible
layerchanged:opacity
layerchanged:index
layeradded
layerremoved 
error

3 - Dispatching the events in other functions (setCenter, setCenterAdvanced, removeImageryLayer, setLayerVisibility etc...)

Tested with ie11, chrome 53 and firefox 38.4

2016-10-11 15:27 UTC, gchoqueux requested changes

2016-10-11 15:27 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +//var eventLayerRemoved = new CustomEvent('Layer-removed');
remove dead code

2016-10-11 15:27 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    //eventLayerChanged.initCustomEvent("layerchanged:index", false, false, false);
remove dead code

2016-10-11 15:27 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +        }else{
Change format
```js
}else{
```

to

```js
} else {
```

2016-10-11 15:27 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    //eventLayerChanged.initCustomEvent("layerchanged:visible", false, false, false);
remove dead code

2016-10-11 15:27 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    eventLayerChanged.layerId = id;
Need Factorization 

Listen all Layers changes (visibilty, opacity, id...) and `dispatchEvent(eventLayerChanged)`

2016-10-11 15:27 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    //eventLayerChanged.initCustomEvent("layerchanged:opacity", false, false, false);
remove dead code

2016-10-11 15:27 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    eventOrientation.oldTilt = this.getTilt();
Why old tilt?

2016-10-11 15:27 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    eventOrientation.oldHeading = this.getHeading();
Why old Heading?

2016-10-11 15:27 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    eventCenter.oldCenter = this.getCenter();
Why old center?

2016-10-11 15:27 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    /*this.viewerDiv.dispatchEvent(eventRange);
remove dead code

2016-10-11 15:27 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    eventRange.oldRange = this.getRange();
why old range?

2016-10-11 15:27 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    this.viewerDiv.dispatchEvent(eventRange);
Need to centralize events -> one event by function

2016-10-11 15:27 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    this.viewerDiv.dispatchEvent(eventLayerChanged);
Centralize event -> one event by function

2016-10-11 15:27 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    this.viewerDiv.dispatchEvent(eventLayerChangedVisible);
Centralize event -> one event by function

2016-10-11 15:27 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    this.viewerDiv.dispatchEvent(eventLayerChangedOpacity);
Centralize event -> one event by function

2016-10-11 15:53 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +ApiGlobe.prototype.addEventListener = function (eventname, callback){
replace by Api function : ` itowns.viewer.addEventListener`

2016-10-11 16:38 UTC, gchoqueux commented on index.html
>          viewerDiv.addEventListener('globe-loaded', function() {
replace by Api function : ` itowns.viewer.addEventListener`

2016-10-11 16:38 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    //eventLayerChanged.initCustomEvent("layerchanged:visible", false, false, false);
Called when the visibility of a layer has changed, return an object with two properties, id and visible

2016-10-11 16:38 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    eventLayerChangedOpacity.layerId = id;
Called when the opacity of a layer has changed, return an object with two properties, id and opacity

2016-10-11 16:38 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    eventLayerChangedIndex.layerId = newId;
Called when the index of a layer has changed, return an object with two properties, id and index

2016-10-12 07:47 UTC, vcoindet commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    eventOrientation.oldTilt = this.getTilt();
@gchoqueux : It was a request from the IGN's Geoportail.

2016-10-12 07:48 UTC, vcoindet commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    eventOrientation.oldHeading = this.getHeading();
@gchoqueux : It was a request from the IGN's Geoportail.

2016-10-12 07:48 UTC, vcoindet commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    eventCenter.oldCenter = this.getCenter();
@gchoqueux : It was a request from the IGN's Geoportail.

2016-10-12 07:48 UTC, vcoindet commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    eventRange.oldRange = this.getRange();
@gchoqueux : It was a request from the IGN's Geoportail.

2016-10-21 09:52 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    this.viewerDiv.dispatchEvent(eventLayerChangedIndex);
place after  `this.scene.getMap().updateLayersOrdering();`

2016-10-21 11:55 UTC, merged