New Api Functions
iTowns/itowns pull request #194
Opened 2016-10-10 10:30 UTC by gchoqueux

Api functions
* ApiGlobe.getZoomScale()
* Add ApiGlobe.setZoomScale(zoomScale)
* Add ApiGlobe.pan(pVector)
* Fix bug ApiGlobe.removeImageryLayer()

* Three js v80 to 81

2016-10-24 14:50 UTC, nosy-b commented
- Error while calling `itowns.viewer.setZoomScale(zoomScale);` directly after loading the globe. If user click and move it then it works.
- `ApiGlobe.prototype.getZoomLevel` has bad documentation and sample code. It doesn"t take any parameters.

2016-10-25 14:08 UTC, gchoqueux commented
@nosy-b see new commits
make `npm install` to check `THREE v82`

2016-10-25 15:35 UTC, nosy-b commented
`ApiGlobe.SetCenter()` works but it doesn't keep camera upVector to current direction (North by default)

Other functions seems to work fine. Remember to add documentation for all functions (at least API ones)

2016-10-26 13:15 UTC, gchoqueux commented
> `ApiGlobe.SetCenter()` works but it doesn't keep camera upVector to current direction (North by default)
use ApiGlobe.setCenterAdvanced() for the moment.
Add a issue for this feature

The branch is updated

2016-10-26 13:40 UTC, peppsac commented on package.json
> +    "three": "^0.82.0",
Is the change intentionnal?
I don't mind upgrading three.js, but you should write about this change in the commit message

2016-10-26 13:40 UTC, peppsac commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +ApiGlobe.prototype.getZoomScale = function(pitch) {
What is the difference betweem zoom *level* and zoom *scale* ?

2016-10-26 13:40 UTC, peppsac commented on src/Scene/LayersConfiguration.js
> +        this.colorLayers = this.colorLayers.filter(function(l) {
The changes to this file should be done in a separate commit.

2016-10-26 14:08 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +ApiGlobe.prototype.getZoomScale = function(pitch) {
ZoomLevel, zoom camera based on level (tile matrix)
ZoomScale, zoom camera based on scale's map

2016-10-26 14:54 UTC, gchoqueux commented
branch updated

2016-10-26 17:43 UTC, peppsac commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +ApiGlobe.prototype.getZoomScale = function(pitch) {
So zoom level is based on WMTS' notion of levels right?

2016-10-27 08:10 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +ApiGlobe.prototype.getZoomScale = function(pitch) {
Zoom level is based level's tile mesh

2016-10-28 15:49 UTC, peppsac commented
It's hard to test this PR: the API is not accessible using the GUI.
Maybe you could add a new `dat.gui` window with a preconfigured action for each API function?

2016-10-28 16:00 UTC, peppsac commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +ApiGlobe.prototype.getZoomScale = function(pitch) {
I get the same result when using `itowns.viewer.setZoomScale(12)` or `itowns.viewer.setZoomScale(0.0000001)`.
But if I use `itowns.viewer.setZoomScale(0.00000001)` I get a black screen and then `setZoomScale` is broken (`rayon` is always `NaN`).

2016-11-03 09:24 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +ApiGlobe.prototype.getZoomScale = function(pitch) {
branch updated

2016-11-03 09:26 UTC, gchoqueux commented
> Maybe you could add a new dat.gui window with a preconfigured action for each API function?

Yes, in new PR. I use console's navigator to test API

2016-11-03 15:00 UTC, gchoqueux commented
branch updated and rebased

2016-11-09 11:07 UTC, gchoqueux commented
r?

2016-11-09 11:09 UTC, peppsac commented
Maybe we could start using label to mark PR that are ready for reviews?

2016-11-09 11:10 UTC, peppsac commented
Anyway I started looking at this one but I got lost investigating errors in `getPickingPosition` while testing:

```js
window.itowns.viewer.setZoomLevel(12)
GlobeControls.js:595 Uncaught TypeError: Cannot read property 'distanceTo' of undefined(…)
```

2016-11-09 13:57 UTC, peppsac requested changes

2016-11-09 13:57 UTC, peppsac commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    zoom = Math.max(2,zoom);
Why do you use a hard-coded level?
You should compute `zoom` using `[getMinZoomLevel(), getMaxZoomLevel()]`

(and I just tested this: these 2 methods are broken :-( )

2016-11-09 13:57 UTC, peppsac commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    // TODO: error is distance is big with ellipsoid.intersection(ray) because d < 0
Typo in the method name `getRangeFromEllispoid` → `getRangeFromEllipsoid`
Also : no documentation? what is the difference between getRange and `getRangeFromEllipsoid`? why/when should I use one or the other?

2016-11-09 13:57 UTC, peppsac commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    let projection;
Would you mind adding some comments about what is going on here?
It's not obvious, even if you're using sensible variable names.

2016-11-09 13:57 UTC, peppsac commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +
Unneeded empty lines + dead code

2016-11-09 13:57 UTC, peppsac commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    let sinBeta = projection / (2 * rayon);
Same: this really needs some comments.

2016-11-09 13:57 UTC, peppsac commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +
Remove empty lines

2016-11-09 13:57 UTC, peppsac commented on src/Globe/Globe.js
> +
3 hard-coded values in a single line: 2 (min level), 18 (max level), 6.0 (sse).

Proposal  : 
* `2` becomes `this.tiles.minLevel`
* `18` becomes `this.tiles.maxLevel`
* `6.0` : you could add a `export const SSE_SUBDIVISION_THRESHOLD` in `NodeProcess.js` and replace all usage of `6.0` in itowns: `NodeProcess.js`, `QuadTree.js` and here.

(and empty blank lines)

2016-11-09 13:57 UTC, peppsac commented on src/Renderer/Camera.js
> +    /*
You're switching back to the old SSE?
Documenting why (in commit message) would be interesting - and maybe change the commit's title btw: you're doing more than juste `AddNew Api Functions`.

2016-11-09 13:57 UTC, peppsac commented on src/Renderer/ThreeExtented/GlobeControls.js
> +            this.camera.up.copy(movingGlobeTarget.clone().normalize());
Again: adding a single line of comment explaining what you're doing here would be useful.
Examples: 
```js
// Rotate globe then update camera to keep camera's center aligned
// Pan camera along globe's normal
```

2016-11-09 13:57 UTC, peppsac commented on src/Renderer/ThreeExtented/GlobeControls.js
> +
Same : add comment please

2016-11-09 13:57 UTC, peppsac commented on src/Renderer/ThreeExtented/GlobeControls.js
> +            this.camera.up.copy(movingGlobeTarget.clone().normalize());
The controls are still buggy (even after this PR: try clicking outside the globe), so adding comments explaining what the code is supposed to do will help us fix the problems.

2016-11-09 13:57 UTC, peppsac commented on src/Renderer/ThreeExtented/GlobeControls.js
> +
Remove blank lines

2016-11-09 13:57 UTC, peppsac commented on src/Renderer/ThreeExtented/GlobeControls.js
> +GlobeControls.prototype.getCenter = function() {
`getCenter`: center of what? center of view? on the globe?
Add a single line of comment or rename using a more descriptive  name

2016-11-09 13:57 UTC, peppsac commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    if (this.scene.getMap().layersConfiguration.removeColorLayer(id)) {
This doesn't fix half of the bugs in `removeImageryLayer` sadly - but I can wait for another PR to fix this.

2016-11-09 15:01 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    if (this.scene.getMap().layersConfiguration.removeColorLayer(id)) {
Yes in is fixed in #200

2016-11-09 16:46 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +
I prefer keep the develop operation to understand : `projection = 2.0 * rayon * Math.sin(phi + alpha);`

2016-11-09 17:17 UTC, gchoqueux commented on src/Renderer/ThreeExtented/GlobeControls.js
> +            this.camera.up.copy(movingGlobeTarget.clone().normalize());
For info on rework GlobeControl see #153 

> try clicking outside the globe

 Can you be more precise for this bug

2016-11-09 17:19 UTC, gchoqueux commented on src/Renderer/ThreeExtented/GlobeControls.js
> +
This part must be reworked

2016-11-09 17:24 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +
ok

2016-11-09 17:27 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    zoom = Math.max(2,zoom);
the previous one was false calculation. I will return it later

2016-11-09 17:27 UTC, gchoqueux commented on src/Renderer/Camera.js
> +    /*
the previous one was false calculation. I will return it later

2016-11-09 17:31 UTC, gchoqueux commented
updated

2016-11-10 09:56 UTC, gchoqueux commented on src/Renderer/Camera.js
> +    /*
I updated the branch with a new commit and a new comment in PR

2016-11-10 10:37 UTC, peppsac requested changes

2016-11-10 10:37 UTC, peppsac commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> + * { Moves a specific layer to a specific index in the layer list. This function has no effect if the layer is moved to its current index. }
Could you remove the `{ }` ?

2016-11-10 10:37 UTC, peppsac commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> + * @param      {number}  newId   The new identifier
Incorrect parameter names:
- `layer` →`layerId`
- `newId` →`newIndex` (and change the documentation accordingly)

2016-11-10 10:37 UTC, peppsac commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    if (this.scene.getMap().layersConfiguration.removeColorLayer(id)) {
Ok 👍

2016-11-10 10:37 UTC, peppsac commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +        return layer.zoom.min;
There are several problems with this function.
1) what is `id` ? `layerIndex` would be a better name (as far as I can tell)
2) what if `id` is invalid ?
3) what if this layer has no zoom property (a `wms` layer for instance ?)
4) no need to modify id, you could use `this.getLayers()[id || 0]`
5) given the function name, maybe you could return the min zoom value for all layers with a zoom value if id is undefined?

2016-11-10 10:37 UTC, peppsac commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +        return layer.zoom.max;
See comments for getMinZoomLevel

2016-11-10 10:37 UTC, peppsac commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +ApiGlobe.prototype.getLayers = function( /*param*/ ) {
`getColorLayers` ? `getImageryLayers` ?

2016-11-10 10:37 UTC, peppsac commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
>   * @param {id} id - The id of the layer.
Remove invalid comments

2016-11-10 10:37 UTC, peppsac commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +ApiGlobe.prototype.getRangeFromEllispoid = function() {
You didn't correct the typo `getRangeFromEllipsoid`

2016-11-10 10:37 UTC, peppsac commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    loaded = false;
Are you sure this is a good idea? I assumed that the `globe-loaded` event was supposed to be fired just once.
If that's not the case maybe documenting each event would be a good idea.

2016-11-10 10:37 UTC, peppsac commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> + * { Displaces the central point to a specific amount of pixels from its current position.
Remove `{  }`

2016-11-10 10:37 UTC, peppsac commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    // C is point in position camera
C = camera's position

2016-11-10 10:37 UTC, peppsac commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    // G is point in globe's center
G = globe's center

2016-11-10 10:37 UTC, peppsac commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    // S is point intersection with surface globe and camera (the furthest from line CG)
S = the furthest interesection[camera frustrum, globe surface]  from line CG

2016-11-10 10:37 UTC, peppsac commented on src/Renderer/Camera.js
> +    /*
You ignored the 2nd part of my comment :)
>Documenting why (in commit message) would be interesting - and maybe change the commit's title btw: you're doing more than juste AddNew Api Functions.

2016-11-10 10:37 UTC, peppsac commented on src/Renderer/Camera.js
> +    var SSE = this.preSSE * (node.geometricError / distance);
Could you add a comment here:
```
// TODO: node.geometricError is computed using a hardcoded 18 level
```

2016-11-10 10:37 UTC, peppsac commented on src/Scene/Quadtree.js
> +            if (SSE_SUBDIVISION_THRESHOLD < node.sse) {
👍

2016-11-10 10:38 UTC, peppsac commented on src/Renderer/Camera.js
> +    /*
Oops, I forgot to read the commit messages.. nevermind :-)

2016-11-10 10:52 UTC, gchoqueux commented on src/Renderer/Camera.js
> +    /*
and I add  link  in [ main comment PR #194](https://github.com/iTowns/itowns2/pull/194#issue-181982034)

2016-11-10 11:44 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    loaded = false;
Yes, the event represents the tiles are loaded. In this case, I need to know when the tiles are loaded to compute the new target camera.

2016-11-10 13:28 UTC, peppsac approved these changes

2016-11-10 13:28 UTC, peppsac commented
Looking better, thanks. Merging

2016-11-10 13:29 UTC, merged