fix(tests): prevent overwriting `navigator.userAgent`
iTowns/itowns pull request #2255
Opened 2024-01-09 13:12 UTC by mgermerie

## Before contributing

- [x] I have read [CONTRIBUTING.md](https://github.com/iTowns/itowns/blob/master/CONTRIBUTING.md) and [CODING.md](https://github.com/iTowns/itowns/blob/master/CONTRIBUTING.md) to apply `iTowns` conventions on PRs, Git history and code.

## Description

As discussed in #2254, the `navigator.userAgent` has been made read-only in [node 21.1.0](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V21.md#2023-10-24-version-2110-current-targos) (see [this commit](https://github.com/nodejs/node/commit/5a52c518ef)).

In this PR, we check if navigator is already set (allegedly by node). If that's the case, we don't overwrite it.

2024-01-10 16:14 UTC, Desplandis requested changes
Tested on node `21.0.0` and latest LTS (`20.11.0`), works like a charm!
Could you please add a notice (see comment)?

2024-01-10 16:14 UTC, Desplandis commented on test/unit/bootstrap.js
> +if (!global.navigator) {
Could you add a notice that such code targets `node < 21.0.0`? This could ease its removal once our minimum node targets will be `>= 21.0.0`. Something like:
```suggestion
// Partial support for global.navigator was added in node 21.0.0
if (!global.navigator) {
```

2024-01-12 09:39 UTC, mgermerie commented on test/unit/bootstrap.js
> +if (!global.navigator) {
Done

2024-01-12 11:46 UTC, Desplandis approved these changes

2024-01-12 11:47 UTC, merged