(PointCloudLayer) add points filtre based on classification
iTowns/itowns pull request #2374
Opened 2024-07-30 09:55 UTC by ftoromanoff

Any classification scheme used for PointCloudLayer havea property 'visible' for each class.
This PR aims at using this value to filter point whichever the visualization mode choosen.

In other word, if a class has its property 'visible' set to false, we want to discard all points having the value in the rendering, (even if we choose to use the 'intensity' rendering)

(In this PR, I used migrate all PointCloud examples to lilGUI instead of datGUI, move to #2546 )

2024-11-04 09:48 UTC, HoloTheDrunk commented
I see we're using a conditional discard in the fragment shader; it might be worth benchmarking the performance of this against using a transparent color or performing the filtering earlier on CPU (which, given the right optimization work, might turn out to be the best solution).
See this (old) SO post for an explanation: https://stackoverflow.com/questions/8509051/is-discard-bad-for-program-performance-in-opengl
This is always going to depend on each user's hardware anyways, but checking wouldn't hurt if we can gain a bit of performance.

2024-11-18 08:43 UTC, Desplandis approved these changes

2024-11-27 16:55 UTC, Desplandis requested changes, later dismissed
Need another review.

2025-05-07 15:32 UTC, AnthonyGlt commented on packages/Main/src/Renderer/PointsMaterial.js
> -        this.userData.needTransparency[PNTS_MODE.CLASSIFICATION] = needTransparency;
It's used in https://github.com/iTowns/itowns/blob/2fae44bf1feb769fedcc52b6ae9045d01f278b4c/packages/Main/src/Layer/ReferencingLayerProperties.js#L61

By doing this, we can't hide specific classes of the 3dtiles

2025-05-21 08:29 UTC, AnthonyGlt reviewed
Thank you for the mr :+1:

2025-05-21 08:29 UTC, AnthonyGlt commented on examples/copc_simple_loader.html
> +        <script src="https://cdn.jsdelivr.net/npm/lil-gui@0.19"></script>
If we change it here, could we not change it in every examples to keep some coherence ?

2025-05-26 08:22 UTC, ftoromanoff commented on examples/copc_simple_loader.html
> +        <script src="https://cdn.jsdelivr.net/npm/lil-gui@0.19"></script>
I will put the 1st commit in a separate PR.

2025-05-26 10:11 UTC, AnthonyGlt approved these changes

2025-05-26 12:54 UTC, merged