getLayers(type)
iTowns/itowns pull request #240
Opened 2017-01-25 17:24 UTC by vcoindet

Return the layers in the scene.
For now, type can be 'colorLayers' or 'elevationLayers', if not specified : returns all the layers.

2017-02-07 14:51 UTC, vcoindet commented
Rebased and Ready

2017-02-20 10:09 UTC, gchoqueux requested changes
do in this PR :

ApiGlobe.prototype.getLayerById()

2017-02-20 10:09 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    const layers = [];
remove `layers`,  it's useless to reconstruct a new Array

2017-02-21 10:27 UTC, vcoindet commented
Changes done @gchoqueux 
rebased and ready

2017-02-24 11:20 UTC, vcoindet commented
rebased

2017-02-28 13:37 UTC, vcoindet commented
rebased

2017-03-03 15:47 UTC, vcoindet commented
rebased and ready @gchoqueux

2017-03-06 09:37 UTC, gchoqueux requested changes

2017-03-06 09:37 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +        return [...lc.getColorLayers(), ...lc.getElevationLayers()];
an geometry layer?

2017-03-06 09:37 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    const tabLayers = [...lc.getColorLayers(), ...lc.getElevationLayers()];
* factorize the aggregate in  `layersConfiguration`
* geometry layer?

2017-03-06 09:37 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    for (const i of tabLayers) {
use `Array.find()`

2017-03-13 10:23 UTC, vcoindet commented
rebased and ready @gchoqueux

2017-03-17 09:49 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    } else if (type === 'colorLayers') {
just replace by color, elevation and geometry

2017-03-17 10:33 UTC, vcoindet commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    } else if (type === 'colorLayers') {
done

2017-03-17 10:35 UTC, vcoindet commented
rebased and ready

2017-03-17 13:52 UTC, gchoqueux approved these changes

2017-03-17 13:52 UTC, merged