doc(test): update command to run one functional test
iTowns/itowns pull request #2418
Opened 2024-09-30 13:14 UTC by jailln

2024-09-30 14:13 UTC, AnthonyGlt requested changes
:+1:

2024-09-30 14:13 UTC, AnthonyGlt commented on CODING.md
> +  `mocha -t 30000 test/functional/hooks_functional.js
```suggestion
  `mocha -t 30000 --require test/functional/hooks_functional.js
```

2024-10-03 11:45 UTC, Desplandis approved these changes

2024-10-03 12:47 UTC, AnthonyGlt approved these changes

2024-10-03 12:47 UTC, merged