refactor(LayeredMaterial): migrate to TypeScript
iTowns/itowns pull request #2477
Opened 2024-12-17 14:56 UTC by HoloTheDrunk

## Description

Converted the `LayeredMaterial` class and eponymous file to TypeScript.
Took this opportunity to do some internal cleanup and refactoring of things like the way the layers (or more precisely `RasterTile`s) were stored, the uniforms and defines, etc... This means the internal API for the material has changed since we now keep `RasterColorTile`s and the one `RasterElevationTile` separate internally. A convenience `getLayer` method has  been provided matching the previous API for cases where the exact type of `RasterTile` is not important.
Whether we should rename the "layer" fields to "tile" to match the actual data type is up for debate. I'm all for it, but I'm not aware of how dependent people might be on those names.

Also planning on making the new uniforms/defines convenience TS-specific functions available to the `PointsMaterial` class and nuking `src/Renderer/CommonMaterial.js` out of existence in a coming PR.

## Motivation and Context
This PR fits into the larger motion to migrate iTowns to TypeScript.

Tested on Ubuntu 22.04.5 LTS x86_64 using Firefox 126.0.1 (64-bit)

2024-12-20 19:20 UTC, jailln commented
Thanks for this PR :) It really makes this material clearer!

I would be down for renaming layer to tile since using layer is really confusing with itowns layers and I think no one is using this API outside of itowns.

I noticed a few bugs though:
* terrain is not displayed anymore: see view_3d_map.html for instance. Also, it seems that now you only let the possibility to have one elevation layer. Even if multiple elevation layers support was not totally implemented (especially when having tiles at the same zoom level or because sometimes we used the first elevation layer by default), it was possible to have two elevation layers.
* debug tiles are always displayed:
![image](https://github.com/user-attachments/assets/f917d132-4bcf-4d80-a745-ddd5c68556a2)
* zoom is broken:

https://github.com/user-attachments/assets/93ac44e8-7aef-4c5b-a423-38d115fd82b3

2024-12-20 20:16 UTC, HoloTheDrunk commented
Hi, yes this is still a WIP and I'm tracking down the source of these issues.
I'll be holiday until early January though so this isn't gonna move much until then.
Happy holidays!

2025-03-18 15:05 UTC, Desplandis requested changes
Good work! I made some suggestions while debugging/reviewing the code.

2025-03-18 15:05 UTC, Desplandis commented on src/Renderer/LayeredMaterial.ts
> +};
This is an enum for effects (i.e. for adding custom shader chunks in `Tile.vs`/`Tile.fs`) in `ColorLayer`, I think this should be `as const`.

2025-03-18 15:05 UTC, Desplandis commented on src/Renderer/LayeredMaterial.ts
> +};
So the `noDataValue` property of the previous default structure was not used?

2025-03-18 15:05 UTC, Desplandis commented on src/Renderer/LayeredMaterial.ts
> +};
This is an enum and it shall be `as const`.

2025-03-18 15:05 UTC, Desplandis commented on src/Renderer/LayeredMaterial.ts
> +        // @ts-expect-error: global constexpr
When you'll rebase on `master`, I suggest adding a `global` declaration in `Main.ts` of the `itowns` package:
```ts
declare global {
  const __DEBUG__: boolean;
}
```

2025-03-18 15:05 UTC, Desplandis commented on src/Renderer/LayeredMaterial.ts
> +    & { uniforms?: MappedUniforms<LayeredMaterialRawUniforms> };
I think it would be easier to read as an extended interface:

```suggestion
export interface LayeredMaterialParameters extends THREE.ShaderMaterialParameters {
    uniforms?: MappedUniforms<LayeredMaterialRawUniforms>;
}
```

Also, do we authorize user of the `LayeredMaterial` class to set its own defines/uniforms?

2025-03-18 15:05 UTC, Desplandis commented on src/Renderer/LayeredMaterial.ts
> +        tile.textureOffset = count;
Yeah, kinda ugly... I don't see where it is passed to the GPU though.

2025-03-18 15:05 UTC, Desplandis commented on src/Renderer/LayeredMaterial.ts
> +    elevationOffsetScales: Array<THREE.Vector4>,
I have a coding-style question (which is kinda orthogonal to this PR), shall we go for `T[]` or `Array<T>` for consistency?

2025-03-18 15:05 UTC, Desplandis commented on src/Renderer/LayeredMaterial.ts
> +        fillInProp(defines, 'DEBUG', +__DEBUG__);
I think it would it be better to just assign the properties directly into `defines`. This would remove the need for type assertions and ease the readability of the code. Something like
```typescript
        const defines: typeof this.defines = {
            NUM_VS_TEXTURES: nbSamplers[0],
            NUM_FS_TEXTURES: nbSamplers[1],
            USE_FOG: 1,
            NUM_CRS: crsCount,
            initModeDefines(),
            MODE: RenderMode.MODES.FINAL,
            DEBUG: __DEBUG__,
        };
        this.defines = defines;
```


You would need to change the `initNodeDefines` to output the key-mapped object for both `ELEVATION_MODES` and `RenderModes.MODES`. Such mapping could be done with
```ts
Object.fromEntries(
        Object.entries(ELEVATION_MODES).map(([key, value]) => [`ELEVATION_${key}`, value])
    ) as { [K in keyof typeof ELEVATION_MODES as `ELEVATION_${K}`]: typeof ELEVATION_MODES[K] }
```

P.S.: I didn't find a way to do such mapping without explicit casts
P.P.S: Forgot to use `DefineMapping` in my suggestion

2025-03-18 15:05 UTC, Desplandis commented on src/Renderer/LayeredMaterial.ts
> +    public override defines: LayeredMaterialDefines;
Why not adding an override for `uniforms` too?

Something like `MappedUniforms<LayeredMaterialRawUniforms>`? `uniforms` would be correctly typed in the whole module.

2025-03-18 15:05 UTC, Desplandis commented on src/Renderer/LayeredMaterial.ts
> +        super(options);
If we wish to let the user provides its own uniforms, it would be better to assign them directly in this class.
```suggestion
        const { uniforms, ...materialOptions } = options;
        super(materialOptions);
```

This would remove the need (in other part of the code) to check if the uniform is already assigned.

2025-03-18 15:05 UTC, Desplandis commented on src/Renderer/LayeredMaterial.ts
> +            this.initUniforms({
In the same vein as my suggestion for `defines`, why not have a single call to `initUniforms` which could return all uniforms and assign the `uniforms` property directly?

2025-03-18 15:05 UTC, Desplandis commented on src/Renderer/LayeredMaterial.ts
> +    }
Any use?

2025-03-19 08:24 UTC, Desplandis commented
@HoloTheDrunk You could fix the zoom and picking bug by correctly assigning the `objectId` uniform in the constructor of `TileMesh`.

```js
material.setUniform('objectId', this.id);
// instead of
material.objectId = this.id;
```

2025-03-19 15:33 UTC, HoloTheDrunk commented on src/Renderer/LayeredMaterial.ts
> +    & { uniforms?: MappedUniforms<LayeredMaterialRawUniforms> };
I don't see a reason to allow custom defines/uniforms given that the pipeline used is fixed (unless the user goes and modifies the shaders, which would be as unintended as can be).

2025-03-19 15:35 UTC, HoloTheDrunk commented on src/Renderer/LayeredMaterial.ts
> +        tile.textureOffset = count;
It's part of the expected fields for a `StructColorLayer`. Seen in `src/Renderer/Shader/Chunk/color_layers_pars_fragment.glsl`.

2025-03-19 15:36 UTC, HoloTheDrunk commented on src/Renderer/LayeredMaterial.ts
> +    elevationOffsetScales: Array<THREE.Vector4>,
I personally prefer the `Array<T>` notation because it's standard with the rest of the type system, but given the ubiquity of arrays it might be better to use `T[]`? I don't really have strong feelings on the matter.

2025-03-19 15:44 UTC, HoloTheDrunk commented on src/Renderer/LayeredMaterial.ts
> +    }
This is provided for users to be able to set uniform values. Should I remove `setUniform` and only keep `setUniforms` or keep both (and use `setUniform` in `setUniforms`)?

2025-03-19 16:15 UTC, HoloTheDrunk commented on src/Renderer/LayeredMaterial.ts
> +};
Unused in the shaders and therefore unnecessary in the uniform structs.

2025-03-20 12:43 UTC, Desplandis commented on src/Renderer/LayeredMaterial.ts
> +        tile.textureOffset = count;
Yeah, but were is it copied?

2025-03-20 12:44 UTC, Desplandis commented on src/Renderer/LayeredMaterial.ts
> +    & { uniforms?: MappedUniforms<LayeredMaterialRawUniforms> };
In that case, you should maybe omit both `uniforms` and `defines` properties.

2025-03-20 12:45 UTC, Desplandis commented on src/Renderer/LayeredMaterial.ts
> +    elevationOffsetScales: Array<THREE.Vector4>,
I usually use `T[]` when T is a single word (or for primitive types) and reserve Array for more complex types.

2025-03-20 16:54 UTC, Desplandis commented on src/Renderer/LayeredMaterial.ts
> +        tile.textureOffset = count;
Okay, we'll resolve it later when we'll document the shaders.

2025-05-28 14:01 UTC, Desplandis approved these changes

2025-05-28 14:02 UTC, merged