New events and events corrections
iTowns/itowns pull request #269
Opened 2017-03-01 11:18 UTC by vcoindet

**Adding the following events** : animationstarted, animationstopped, zoomchanged

**Modifications on the following events : ** layerchanged, layerchanged:visible, layerchanged:opacity, layerchanged:index, orientationchanged, layeradded

2017-03-08 14:12 UTC, vcoindet commented
Rebased and Ready

2017-04-04 13:53 UTC, gchoqueux requested changes

2017-04-04 13:53 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +const logStep = function logStep(step) {
remove

2017-04-04 13:53 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    detail: {
replace by `detail: {old: {},new: {}},`

2017-04-04 13:53 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    eventLayerChanged.detail.opacity.oldOpacity = this.scene.getMap().layersConfiguration.getColorLayerOpacity(layerId);
factorize

2017-04-04 13:53 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    eventLayerChanged.detail.index.oldIndex = this.scene.getMap().layersConfiguration.layersState[id].sequence;
factorize

2017-04-04 13:53 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    eventLayerChanged.detail.index.oldIndex = this.scene.getMap().layersConfiguration.layersState[id].sequence;
factorize

2017-04-04 13:53 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    eventCenter.detail.oldCenter.longitude = this.getCenter()._values[0] * 180 / Math.Pi;
Math.Pi???

2017-04-04 13:53 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +            eventCenter.detail.newCenter.longitude = this.getCenter()._values[0] * 180 / Math.Pi;
use Coordinates functions

2017-04-04 13:53 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +ApiGlobe.prototype.testEvents = function testEvents(eventname, param) {
remove and keep in you side

2017-04-05 17:34 UTC, vcoindet commented
rebased and ready @gchoqueux

2017-04-06 12:13 UTC, gchoqueux requested changes

2017-04-06 12:13 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    detail: { new: {}, old: {} },
create object `statut`
 
detail : new statut(),

2017-04-06 12:13 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +ApiGlobe.prototype.getOldStatusLayer = function getOldStatusLayer(layerId) {
Only one function is required `getStatusLayer`, no?

2017-04-06 12:13 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    eventLayerChanged.detail.opacity.old = this.scene.getMap().layersConfiguration.getColorLayerOpacity(layerId);
`eventLayerChanged.detail.opacity.old` or `eventLayerChangedOpacity.detail.old`
need homogenized details

2017-04-06 12:13 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    this.getCenterStatus('new');
and the old statut?

2017-04-06 12:13 UTC, gchoqueux commented on src/Renderer/ThreeExtended/GlobeControls.js
> +        rot.x = globeTarget.rotation._x;
not correct, i think is more `spherical` member

2017-04-06 12:13 UTC, gchoqueux commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +ApiGlobe.prototype.selectNodeById = function selectNodeById(id) {
Why you add this?

2017-04-06 12:41 UTC, vcoindet commented on src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js
> +    this.getCenterStatus('new');
No need here, it's just a initialization so the old status will be good in the function `callbackCenterChanged`

It's the same for the events `zoomchanged` and `orientationchanged`

2017-04-06 14:05 UTC, autra commented
2 important points:

- A lot of boilerplate would have been spared if you didn't try to create events as constants... Also doing so is dangerous: sharing them as it is done here (and in itowns currently) is a risk of data leakage and of collision. Just create them when you fire them. Events are not made to be shareable like that. 

It would be simpler and safer and would avoid having stuff like the `status` function, that really does nothing.

*  even if there might be exceptions. ApiGlobe should *not* fire any events : it's proxying stuff to the underlying services (Scene, GlobeControls) etc and *they* should fire events. The point of events is to notify client of changes that itowns is doing without the client knowing *or* to notify them of any asynchronous action that have been completed.

For example: `moveLayerUp` is not asynchrone AND is called *by* the client. The client code (geoportail, or anything else) already *knows* about the change. It simply doesn't make sense to fire an event there. Other examples of useless events : all the setLayer* methods,

2017-04-06 14:06 UTC, autra commented
> it's proxying stuff to the underlying services (Scene, GlobeControls) etc and they should fire events

*if* there is an asynchrone process of course.

2017-05-18 17:02 UTC, gchoqueux commented
moved in #306 and #298

2017-05-18 17:02 UTC, closed without merging