Webpack2
iTowns/itowns pull request #283
Opened 2017-04-07 08:12 UTC by autra

Webpack 1 is deprecated, so let's update. First commit fixes the indentation of `webpack.config.js`, so looking at second commit only might be better to review changes.

@iTowns/reviewers please r?

2017-04-07 09:15 UTC, tbroyer requested changes

2017-04-07 09:15 UTC, tbroyer commented on package.json
>      "babel-loader": "^6.2.10",
Update all Webpack loaders to their latest version that explicitly support Webpack 2? (eslint-loader → 1.7.1 ; imports-loader → 0.7.1) Should we use the 7.0.0-beta.1 for babel-loader or live with the deprecation warning with 6.x?

2017-06-01 07:50 UTC, autra commented on package.json
>      "babel-loader": "^6.2.10",
Resuming work on this. Yes, I'm upgrading everything. babel-loader 7 is now stable fortunately.

2017-06-01 10:46 UTC, tbroyer approved these changes

2017-06-02 08:57 UTC, merged