Move controls function to globeControls
iTowns/itowns pull request #298
Opened 2017-05-09 16:15 UTC by gchoqueux

2017-05-12 07:31 UTC, peppsac requested changes
Thanks for the PR, it looks like a good idea.

I've left a few comments, mainly related to event naming.

2017-05-12 07:31 UTC, peppsac commented on src/Scene/AnimationPlayer.js
> +            type: 'endedAnimation',
`animation-ended` ?

2017-05-12 07:31 UTC, peppsac commented on src/Scene/AnimationPlayer.js
> +        type: 'stopedAnimation',
`animation-stopped` ?

2017-05-12 07:31 UTC, peppsac commented on src/Scene/AnimationPlayer.js
> +            type: 'playAnimation',
`animation-started` ? (events are things that happened, so they can really start with a verb)

2017-05-12 07:31 UTC, peppsac commented on src/Scene/AnimationPlayer.js
> +                type: 'frameAnimation',
`animation-frame` ?

2017-05-12 07:31 UTC, peppsac commented on src/Scene/AnimationPlayer.js
> +class AnimationPlayer extends THREE.EventDispatcher {
Good idea to use `EventDispatcher`

2017-05-12 07:31 UTC, peppsac commented on src/Renderer/ThreeExtended/GlobeControls.js
> +                type: 'orientationchanged',
`orientation-changed` ? (uniform naming scheme for all events)

2017-05-12 07:31 UTC, peppsac commented on src/Renderer/ThreeExtended/GlobeControls.js
> +                type: 'panchanged',
`pan-changed`

2017-05-12 07:31 UTC, peppsac commented on src/Renderer/ThreeExtended/GlobeControls.js
> +                old: { range: oldRange },
`range-changed`.
Also I think `previous` is better than `old`. WDYT?

2017-05-12 07:31 UTC, peppsac commented on src/Renderer/ThreeExtended/GlobeControls.js
> +                old: { cameraTargetPosition: C.fromXYZ(scene.referenceCrs, oldCameraTargetOnGlobe) },
There should be some coherency between the event name and the attribute content, to ease API usage.
If the event is `camera-target-updated` (I think I'd prefer `-changed` btw), the expected attribute would be: `event.new.cameraTarget`

2017-05-12 07:31 UTC, peppsac commented on src/Renderer/ThreeExtended/GlobeControls.js
> +                    type: 'rangechanged',
`range-changed`

2017-05-12 07:31 UTC, peppsac commented on src/Renderer/ThreeExtended/GlobeControls.js
> +    player.addEventListener('playAnimation', (e) => {
What's the point of this code?

2017-05-12 07:31 UTC, peppsac commented on src/Renderer/ThreeExtended/GlobeControls.js
> +    function asAnimation(animation) {
What is this function doing?

2017-05-12 07:31 UTC, peppsac commented on src/Renderer/ThreeExtended/GlobeControls.js
> +                type: 'animationstarted',
`animation-started`

2017-05-12 07:31 UTC, peppsac commented on src/Renderer/ThreeExtended/GlobeControls.js
> +                type: 'animationended',
`animation-ended`

2017-05-12 07:31 UTC, peppsac commented on src/Renderer/ThreeExtended/GlobeControls.js
> +GlobeControls.prototype.setSceneLoaded = function setSceneLoaded() {
Why is this function in `GlobeControls` prototype (ie : do you really want to expose it outside of this module)?

2017-05-12 08:38 UTC, vcoindet commented on src/Renderer/ThreeExtended/GlobeControls.js
> +GlobeControls.prototype.setCameraTargetGeoPosition = function setCameraTargetGeoPosition(coordinates, isAnimated) {
Doesn't do anything when called in index.html when animation is set to true. (works when animation is set to false)

Works fine in console.

2017-05-12 08:38 UTC, vcoindet commented on src/Renderer/ThreeExtended/GlobeControls.js
> +GlobeControls.prototype.setCameraTargetGeoPositionAdvanced = function setCameraTargetGeoPositionAdvanced(position, isAnimated) {
same as `setCameraTargetGeoPosition()`

2017-05-12 08:46 UTC, gchoqueux commented on src/Renderer/ThreeExtended/GlobeControls.js
> +    player.addEventListener('playAnimation', (e) => {
Ability to listen  the starting and ending of the control's animations

2017-05-12 10:27 UTC, gchoqueux commented on src/Renderer/ThreeExtended/GlobeControls.js
> +GlobeControls.prototype.setCameraTargetGeoPosition = function setCameraTargetGeoPosition(coordinates, isAnimated) {
@vcoindet 
need a new issue same problem in master (synchronization problem)

2017-05-12 12:12 UTC, vcoindet commented on src/Renderer/ThreeExtended/GlobeControls.js
> +                type: 'range-changed',
this event is dispatched twice when range =< 10000 in `setCameraTargetGeoPosition`

2017-05-12 12:12 UTC, vcoindet commented on src/Renderer/ThreeExtended/GlobeControls.js
> +    player.addEventListener('animation-ended', (e) => {
'`animation-started`' and '`animation-ended`' are dispatched twice when `setCameraTargetGeoPositionAdvanced(position, true)` is called

2017-05-17 16:12 UTC, gchoqueux commented on src/Renderer/ThreeExtended/GlobeControls.js
> +    player.addEventListener('animation-ended', (e) => {
done

2017-05-17 16:23 UTC, gchoqueux commented
@peppsac branch updated

2017-05-18 08:05 UTC, peppsac requested changes
Thanks for the changes.
This PR is looking good overall (though I just skimmed over GlobeControls changes).

Still a few things to address and this will be ok.

2017-05-18 08:05 UTC, peppsac commented on src/Renderer/ThreeExtended/GlobeControls.js
> +export const CONTROL_EVENT = {
Maybe add a `s` since there are several events: `CONTROL_EVENTS`

2017-05-18 08:05 UTC, peppsac commented on src/Renderer/ThreeExtended/GlobeControls.js
> +    CAMERATARGET_CHANGED: 'camera-target-changed',
`CAMERA_TARGET_CHANGED` to use the same naming scheme.

2017-05-18 08:05 UTC, peppsac commented on src/Renderer/ThreeExtended/GlobeControls.js
> +const defer = function defer() {
Why don't you simply declare `defer` as:
```js
function defer() {
   ...
}
``` 
?

2017-05-18 08:05 UTC, peppsac commented on src/Renderer/ThreeExtended/GlobeControls.js
> +            globeLoadedDeferred.resolve();
What if `globeLoadedDeferred.resolve` is undefined?

2017-05-18 08:05 UTC, peppsac commented on src/Renderer/ThreeExtended/GlobeControls.js
> +let globeLoadedDeferred = defer();
What's the point of initializing `globeLoadedDeferred` like this?

Here are 2 alternative proposal, that share a single objective: remove the `globeLoadedDeferred` var.

```js
// replace setSceneLoaded by:
function waitSceneLoaded() {
    const deferedPromise = defer();
    onNextSceneLoadedCb.push(deferedPromise);
    globeIsLoaded = false;
    return deferedPromise.promise;
}
// and use like your setSceneLoaded:
waitSceneLoaded().then(() => { ... }
```
2nd option, even simpler (my favorite):
```js
function onSceneLoaded(fn) {
    onNextSceneLoadedCb.push(fn);
    globeIsLoaded = false;
}
// usage:
onSceneLoaded(() => {
    this.updateCameraTransformation();
    this.dispatchEvent(this.changeEvent);
});
```

2017-05-18 08:05 UTC, peppsac commented on src/Renderer/ThreeExtended/GlobeControls.js
> +    return C.fromXYZ('EPSG:4978', pickedPosition).as('EPSG:4326');
Use the constructor instead:
```js
new Coordinates('EPSG:4978', pickedPosition).as('EPSG:4326');
```

2017-05-18 10:06 UTC, gchoqueux commented
@peppsac branch updated

2017-05-18 10:06 UTC, gchoqueux commented on src/Renderer/ThreeExtended/GlobeControls.js
> +export const CONTROL_EVENT = {
done

2017-05-18 10:06 UTC, gchoqueux commented on src/Renderer/ThreeExtended/GlobeControls.js
> +    CAMERATARGET_CHANGED: 'camera-target-changed',
done

2017-05-18 10:07 UTC, gchoqueux commented on src/Renderer/ThreeExtended/GlobeControls.js
> +const defer = function defer() {
done

2017-05-18 10:07 UTC, gchoqueux commented on src/Renderer/ThreeExtended/GlobeControls.js
> +let globeLoadedDeferred = defer();
thanks

2017-05-18 10:07 UTC, gchoqueux commented on src/Renderer/ThreeExtended/GlobeControls.js
> +    return C.fromXYZ('EPSG:4978', pickedPosition).as('EPSG:4326');
done

2017-05-18 12:00 UTC, peppsac requested changes
Almost there.

Some of the functions are badly named (e.g `getRange`) but this is not the purpose of this PR so finding a better name can wait.

2017-05-18 12:00 UTC, peppsac commented on src/Renderer/ThreeExtended/GlobeControls.js
> +    return C.fromXYZ('EPSG:4978', this.camera.position).as('EPSG:4326');
`C.fromXYZ`  doesn't exist. You can use `new Coordinates('EPSH:4978', this.camera.position)` instead

2017-05-18 12:00 UTC, peppsac commented on src/Renderer/ThreeExtended/GlobeControls.js
> +    onNextSceneLoadedCb.push(deferedPromise);
Note that you could even simplify this by doing:
```js
function waitSceneLoaded(viewerDiv) {
    const deferedPromise = defer();
    viewerDiv.addEventListener('globe-built', () => {
       deferedPromise.resolve();
   });
   return deferedPromise;
}
```
That would remove the sketchy `globeIsLoaded` variable as well.

(remember that all these global variables will cause trouble when trying to create 2 GlobeControls, see multiglobe example)

2017-05-18 13:12 UTC, gchoqueux commented on src/Renderer/ThreeExtended/GlobeControls.js
> +    onNextSceneLoadedCb.push(deferedPromise);
done

2017-05-18 13:13 UTC, gchoqueux commented on src/Renderer/ThreeExtended/GlobeControls.js
> +    return C.fromXYZ('EPSG:4978', this.camera.position).as('EPSG:4326');
done

2017-05-18 13:13 UTC, gchoqueux commented
@peppsac last comments updated

2017-05-18 13:26 UTC, peppsac approved these changes

2017-05-18 13:26 UTC, peppsac commented
Looks good, merging.

2017-05-18 13:26 UTC, merged