Refacto layer
iTowns/itowns pull request #301
Opened 2017-05-12 14:05 UTC by peppsac

(Last) core refactoring of itowns.

Most important commit is: c0cfb0b7a74fb6ebe6af9b7e0cde8704f2fdde95
```
    refactor: remove Scene and reorganize files
    
    Split Scene responsabilities between:
      * View: container for datas
      * MainLoop: itowns' main loop (update/render)
    
    GlobeView is a specialized View, ready for displaying a Globe.
    c3DEngine also loses Globe-related code, which moves to GlobeView.
    
    Files/folders hierarchy has changed as well.
```

This PR also adds 2 examples:
* `planar.html`: itowns in planar mode (EPSG:3946)
* `multiglobe.html`: shows 2 itowns globes on the same page (note: debug and controls are buggy in this example)

2017-05-12 16:45 UTC, Jeremy-Gaillard reviewed
Just a few things I noticed while working on the 3d-tiles branch, I haven't actually read the whole PR.

2017-05-12 16:45 UTC, Jeremy-Gaillard commented on src/Core/Prefab/PlanarView.js
> +PlanarView.prototype.addLayer = function addLayer(layer) {
I have an issue with the overriding of this function. If I want to add a layer that is independent from the plane itself (a 3d-tile layer in my case), I no longer can add it to the view without attaching it to the terrain tile layer.

2017-05-12 16:45 UTC, Jeremy-Gaillard commented on src/Main.js
> +// Modules using `default` export must be imported...
Some exports are missing (GeometricLayer for example). I think a good test to see if enough classes are exposed is to try to recreate PlanarView or GlobeView from outside the core.

2017-05-12 16:45 UTC, Jeremy-Gaillard commented on src/Process/GlobeTileProcessing.js
>  let vhMagnitudeSquared;
Won't these global variables mess things up when having multiple instances of iTowns? It shouldn't affect anything if the instances have the same window size though.

2017-05-12 16:47 UTC, peppsac commented on src/Core/Prefab/PlanarView.js
> +PlanarView.prototype.addLayer = function addLayer(layer) {
Yes you can, using:
```js
itowns.View.prototype.addLayer.call(view, pointcloud);
```
The syntax is special, but it's an advanced use case so I don't mind it.

2017-05-12 16:48 UTC, peppsac commented on src/Main.js
> +// Modules using `default` export must be imported...
I'll add an advanced example without using `PlanarView` or `GlobeView` so I'll need to update exports.
It might end up in a separate PR though.

2017-05-12 16:49 UTC, peppsac commented on src/Process/GlobeTileProcessing.js
>  let vhMagnitudeSquared;
Yes this is a problem.
This is the same reason that makes the globe controls behave weirdly in the `multiglobe` example.

2017-05-15 12:27 UTC, gchoqueux commented on src/Process/LayeredMaterialNodeProcessing.js
> +            min: parent.OBB().z.min,
Seems useless because already done [here](https://github.com/iTowns/itowns2/pull/301/files#diff-48576d3351459435df139556b817119dR65)

2017-05-15 13:02 UTC, gchoqueux commented
In Viewer, how remove layer and ordered layer?

2017-05-15 13:04 UTC, peppsac commented on src/Process/LayeredMaterialNodeProcessing.js
> +            min: parent.OBB().z.min,
Thanks, fixed.

2017-05-15 13:06 UTC, gchoqueux commented
Bugs :
* Imagery layer are downscaled
* problem with right clic (context menu appears)
* The selection of tiles doesn't work all the time (May reveal a refresh problem)

2017-05-15 13:13 UTC, gchoqueux commented
It seems to have problems with `colorLayersId` and`layerTexturesCount` 

`colorLayersId` can have unnecessary  color layers -> The LayeredMaterialNodeProcessing must have introduced an error.

2017-05-15 13:16 UTC, gchoqueux commented
don't forget to update `examples/index.hmtl`

2017-05-15 13:32 UTC, gchoqueux commented
It seems to have problems with `colorLayersId` and`layerTexturesCount` 

`colorLayersId` can have unnecessary  color layers -> The `LayeredMaterialNodeProcessing` must have introduced an error.

Example :
For one tile on france with tile's zoom === 3
   * tile.material.colorLayersId === ["Ortho", "OrthoCRS", "ScanEX", "Region"]
   * tile.material.layerTexturesCount === [3, 1, 3, 1]

While the layer `OrthoCRS` starts at zoom 6

2017-05-15 13:35 UTC, peppsac commented
New update pushed.
The issues that should be fixed are:
* Imagery layer are downscaled (from https://github.com/iTowns/itowns2/pull/301#issuecomment-301469083)
* The selection of tiles doesn't work all the time (May reveal a refresh problem)  (from https://github.com/iTowns/itowns2/pull/301#issuecomment-301469083)
* Some exports are missing (GeometricLayer for example). (from https://github.com/iTowns/itowns2/pull/301#discussion_r116273196)
* don't forget to update examples/index.hmtl (from https://github.com/iTowns/itowns2/pull/301#issuecomment-301471619)

2017-05-15 14:57 UTC, peppsac commented
Pushed a fix for: 

- colorLayersId can have unnecessary color layers (from https://github.com/iTowns/itowns2/pull/301#issuecomment-301475771)

2017-05-15 15:33 UTC, gchoqueux commented
**bug** resize windows : the layers aren't updated before rendering (the frustrum culling is updated after rendering)

2017-05-16 08:28 UTC, peppsac commented
New update. I've fixed a few bugs regarding layers ordering.

@gchoqueux regarding "In Viewer, how remove layer and ordered layer?" : see how's ApiGlobe is doing it now.

2017-05-16 09:37 UTC, peppsac commented
New update and "bug resize windows : the layers aren't updated before rendering (the frustrum culling is updated after rendering)" (from https://github.com/iTowns/itowns2/pull/301#issuecomment-301512331) is fixed.

2017-05-16 12:26 UTC, gchoqueux commented
Tile's DMT can flick when user zoom and stop navigation

2017-05-16 12:27 UTC, gchoqueux commented
Why realistic lighting is broken?

2017-05-16 12:32 UTC, gchoqueux commented
2 problems with GUI:
* Right clic can make appear a context menu (instead of paning)
* If we close, open Gui controls and move globe : can make select text in Gui (instead of moving globe)

2017-05-16 14:21 UTC, peppsac commented
Update++
Issues fixed:
* Tile's DMT can flick when user zoom and stop navigation (https://github.com/iTowns/itowns2/pull/301#issuecomment-301766087)
* Why realistic lighting is broken? (https://github.com/iTowns/itowns2/pull/301#issuecomment-301766223)

I can't reproduce the 2 "GUI" issues  from https://github.com/iTowns/itowns2/pull/301#issuecomment-301767534 - can you still reproduce them?

2017-05-16 15:00 UTC, gchoqueux commented
All Layer.sequence aren't updated when we remove imagery layer

2017-05-16 15:49 UTC, peppsac commented
"All Layer.sequence aren't updated when we remove imagery layer" (https://github.com/iTowns/itowns2/pull/301#issuecomment-301810085) fixed as well

2017-05-17 08:48 UTC, gchoqueux requested changes

2017-05-17 08:48 UTC, gchoqueux commented on src/Renderer/c3DEngine.js
> +        if (camera.camHelper())
remove camHelper()

2017-05-17 08:48 UTC, gchoqueux commented on src/Renderer/c3DEngine.js
>          this.width = this.viewerDiv.clientWidth * (this.debug ? 0.5 : 1);
replace by `this.width = this.viewerDiv.clientWidth`

2017-05-17 08:48 UTC, gchoqueux commented on src/Core/View.js
> +        this._debug = new Debug(this, viewerDiv);
this._debug is used?

2017-05-17 08:48 UTC, gchoqueux commented on src/Core/View.js
> +function _preprocessLayer(view, layer, provider) {
`_preprocessLayer` We will see later but this function does things too specific

2017-05-17 08:48 UTC, gchoqueux commented on src/Core/View.js
> +View.prototype.addLayer = function addLayer(layer, parentLayer) {
Note:
`addLayer` but there's not removeLayer

2017-05-17 08:48 UTC, gchoqueux commented on src/Core/View.js
> +View.prototype.initDefaultProviders = function initDefaultProviders(scheduler) {
`initDefaultProviders` move in Scheduler? or create provider when is necessary

2017-05-17 08:48 UTC, gchoqueux commented on src/Core/View.js
> +View.prototype.getLayers = function getLayers(filter) {
comment filter use

2017-05-17 08:48 UTC, gchoqueux commented on src/Core/Scheduler/Interfaces/ApiInterface/ApiGlobe.js
> +ApiGlobe.prototype.animateTime = function animateTime(value) {
remove animateTime

2017-05-17 08:48 UTC, gchoqueux commented on src/Core/Scheduler/Interfaces/ApiInterface/ApiGlobe.js
> +ApiGlobe.prototype.orbit = function orbit(value) {
remove orbit

2017-05-17 08:48 UTC, gchoqueux commented on src/Core/MainLoop.js
> +        // TODO per view
This event is important, it can't be removed

2017-05-17 08:50 UTC, peppsac commented on src/Renderer/c3DEngine.js
> +        if (camera.camHelper())
done

2017-05-17 08:52 UTC, peppsac commented on src/Renderer/c3DEngine.js
>          this.width = this.viewerDiv.clientWidth * (this.debug ? 0.5 : 1);
done

2017-05-17 08:53 UTC, peppsac commented on src/Core/View.js
> +        this._debug = new Debug(this, viewerDiv);
Nope and Debug is a plain function, not a constructor so  I need to this this... thanks.

2017-05-17 08:53 UTC, peppsac commented on src/Core/View.js
> +function _preprocessLayer(view, layer, provider) {
Agreed

2017-05-17 08:54 UTC, peppsac commented on src/Core/View.js
> +View.prototype.addLayer = function addLayer(layer, parentLayer) {
Yeah... mainly because the main usage is to add layers.
We'll probably want to add a `removeLayer` method layer though.

2017-05-17 08:56 UTC, peppsac commented on src/Core/View.js
> +View.prototype.initDefaultProviders = function initDefaultProviders(scheduler) {
Hmm ok, moving this to Scheduler.

2017-05-17 09:01 UTC, peppsac commented on src/Core/View.js
> +View.prototype.getLayers = function getLayers(filter) {
Done

2017-05-17 09:02 UTC, peppsac commented on src/Core/Scheduler/Interfaces/ApiInterface/ApiGlobe.js
> +ApiGlobe.prototype.animateTime = function animateTime(value) {
Done

2017-05-17 09:02 UTC, peppsac commented on src/Core/Scheduler/Interfaces/ApiInterface/ApiGlobe.js
> +ApiGlobe.prototype.orbit = function orbit(value) {
Done

2017-05-17 09:17 UTC, peppsac commented on src/Core/MainLoop.js
> +        // TODO per view
Fixed.

2017-05-17 09:17 UTC, peppsac commented
New update, fixing all your comments @gchoqueux :)

2017-05-17 11:01 UTC, gchoqueux approved these changes

2017-05-17 11:05 UTC, merged

2017-05-17 11:12 UTC, vpicavet commented
Thanks for the awesome work on this ! Now heading towards a great framework !