Functionnal testing based on examples
iTowns/itowns pull request #324
Opened 2017-06-01 16:28 UTC by peppsac

Here's a PR which implements some basic functionnal testing using examples.

Examples are run using `mocha` + `node`, and some basic checks are implemented for each example.

The point is to basically make sure iTowns still work on each example in a quick way, even if we don't exercise the full stack.

WDYT?

2017-06-01 16:29 UTC, peppsac commented
I forgot something: you can test using the new `npm run test-examples` command :)

2017-06-07 08:49 UTC, peppsac commented
It seems that nobody is interested in testing... I should have used a fork of an obscure test framework instead of the standard one; I'm sure it would have generated a lot of comments :-)

2017-06-07 09:13 UTC, gchoqueux commented
yes, I'am interesting, I will be regarding soon
I have too a PR on test #275

2017-06-08 09:35 UTC, gchoqueux requested changes

2017-06-08 09:35 UTC, gchoqueux commented on examples/planar.js
> +// # Planar (EPSG:3946) viewer
in browser `/examples/planar.html` have error 
`Uncaught ReferenceError: bbox is not defined`

2017-06-08 09:35 UTC, gchoqueux commented on examples/postprocessing.js
> +exports.globeView = globeView;
error `exports` not define in browser

2017-06-08 09:35 UTC, gchoqueux commented on test/externalscene_test.js
> +        example.globeView.mainLoop.addEventListener('command-queue-empty', () => {
You could use this event?
`example.globeView.addEventListener(itowns.GLOBE_VIEW_EVENTS.GLOBE_INITIALIZED`...

2017-06-08 09:35 UTC, gchoqueux commented on test/globe_test.js
> +                example.view.notifyChange(true);
why you use `notifyChange`?

2017-06-08 09:35 UTC, gchoqueux commented on examples/externalscene.js
> +viewerDiv.appendChild(renderer.domElement);
in browser `renderer` is undefined

2017-06-08 09:35 UTC, gchoqueux commented on examples/globe.js
> +exports.view = globeView;
`exports` is undefined in browser

2017-06-08 14:53 UTC, peppsac commented on test/externalscene_test.js
> +        example.globeView.mainLoop.addEventListener('command-queue-empty', () => {
Hmm for no particular reason, both are equivalent.

2017-06-08 14:54 UTC, peppsac commented
Fixed all your comments.

2017-06-08 15:49 UTC, gchoqueux approved these changes

2017-06-08 15:50 UTC, gchoqueux commented
needs rebasing

2017-06-09 13:16 UTC, peppsac commented
The tests have a different behavior on Travis (failure).
I'm trying to figure out what causes the difference - let me know if you have any ideas (or if the tests fail on your computer).

2017-06-09 13:42 UTC, tbroyer commented
Same error on my machine (node v8.0.0, npm v5.0.0)

2017-06-09 14:01 UTC, peppsac commented
Thanks I can reproduce it here with the same node version and I think I understood the root issue.

2017-06-09 14:12 UTC, tbroyer commented
FWIW, those tests are non-deterministic. Here's the same test run 3 times in a row:
```
$ mocha test/globe_test.js


  Globe example
Globe initialized
(node:13887) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: this.renderer.setScissor is not a function
(node:13887) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:13887) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: this.material.setTexturesLayer is not a function
(node:13887) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: this.material.setTexturesLayer is not a function
(node:13887) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): TypeError: this.material.setTexturesLayer is not a function
(node:13887) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): TypeError: this.material.setTexturesLayer is not a function
    ✓ should subdivide like expected (137ms)


  1 passing (252ms)

$ mocha test/globe_test.js


  Globe example
Globe initialized
(node:13911) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: this.renderer.setScissor is not a function
(node:13911) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    ✓ should subdivide like expected (140ms)


  1 passing (255ms)

$ mocha test/globe_test.js


  Globe example
Globe initialized
(node:13932) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: this.renderer.setScissor is not a function
(node:13932) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    1) should subdivide like expected


  0 passing (2s)
  1 failing

  1) Globe example should subdivide like expected:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

2017-06-09 14:14 UTC, peppsac commented
From the beginning I've made these tests more and more deterministic: I won't merge tests that sometimes work, sometimes don't.

I'll push a new version soon, let me know if they work better.

2017-06-09 14:52 UTC, peppsac commented
Should be fixed now.
@tbroyer let me know if it's still unreliable on your setup, thanks!

2017-06-09 15:07 UTC, tbroyer commented
Appears to work reliably now.

2017-06-09 17:06 UTC, merged