feature: add TMS_Provider
iTowns/itowns pull request #340
Opened 2017-06-19 20:20 UTC by peppsac

Add TMS_Provider and a simple example to display OSM map à la OpenLayers

2017-06-26 10:42 UTC, peppsac commented
Added a example that uses the `TMS_Provider`.

2017-06-27 13:54 UTC, autra requested changes

2017-06-27 13:54 UTC, autra commented on examples/orthographic.html
> +            let renderer;
Why do you need this here?

2017-06-27 13:54 UTC, autra commented on examples/orthographic.js
> +/* global itowns, document, renderer */
If you do `let renderer` here, you don't need it in global. Also I'm suprised to see `document` here. eslint knows about `document` being global :-)

2017-06-27 13:54 UTC, autra commented on examples/orthographic.js
> +view.tileLayer.disableSkirt = true;
I think this `disableSkirt` is not obvious to the newcomers. Can you add a comment to explain why it's needed?

2017-06-27 13:54 UTC, autra commented on src/Core/Geographic/Extent.js
> +function _crsIsWMTSorTMS(crs) {
`_crsIsTiled`?

2017-06-27 13:54 UTC, autra commented on src/Core/Scheduler/Providers/OGCWebServiceHelper.js
> +    computeTMSCoordinates(tile, extent) {
A bit of doc?

2017-06-27 13:54 UTC, autra commented on src/Core/Scheduler/Providers/OGCWebServiceHelper.js
> +        const y = (1 - c.y() / (layerDimension.y * 0.5)) * 0.5;
does this suppose that the origin is at the center of the extent? Is it a correct assumption?

2017-06-27 13:54 UTC, autra commented on src/Core/Scheduler/Providers/TMS_Provider.js
> +            max: 18,
`getCapabilities`... I forgot about this one. I need to resume the work on that.

2017-06-27 13:54 UTC, autra commented on src/Core/Scheduler/Providers/TMS_Provider.js
> +        undefined;
So this is : "if the requested level is less than my current level, then let's find out which one of my parents is on this level". That's it? 

How is it possible that the requester ask for a level lower than its own? For some network strategy like dichotomy?

2017-06-27 14:07 UTC, peppsac commented on examples/orthographic.html
> +            let renderer;
It's not needed yet... it's only needed to write a test using this example.

2017-06-27 14:08 UTC, peppsac commented on src/Core/Scheduler/Providers/TMS_Provider.js
> +        undefined;
Yes. And Yes. :)

2017-06-27 14:31 UTC, peppsac commented on src/Core/Scheduler/Providers/OGCWebServiceHelper.js
> +        const y = (1 - c.y() / (layerDimension.y * 0.5)) * 0.5;
There's no particular assumption, except that `c` is inside the `layer`

2017-06-27 14:37 UTC, peppsac commented
Thanks @autra 
I've updated the branch.

2017-06-28 09:44 UTC, peppsac commented on src/Core/Scheduler/Providers/OGCWebServiceHelper.js
> +        const y = (1 - c.y() / (layerDimension.y * 0.5)) * 0.5;
Ok understood what you meant, and I rewrote the code to be clearer (I hope).

2017-06-28 14:56 UTC, autra approved these changes

2017-06-28 14:58 UTC, autra commented
LGTM, thanks! Please rebase :-)

2017-06-28 16:02 UTC, merged