feature: 3dtiles file: pnts and b3dm RTC feature
iTowns/itowns pull request #352
Opened 2017-06-29 07:47 UTC by NikoSaul

2017-06-29 09:34 UTC, peppsac requested changes
Thanks, looks good.
Just a few comments to address before merging :)

2017-06-29 09:34 UTC, peppsac commented on src/Core/Scheduler/Providers/3dTiles_Provider.js
> +        let url = metadata.urlPrefix + urlSuffix;
Is this code trying to find out if `urlSuffix` is a relative or absolute url?

Maybe worth adding a comment specifying why you're doing this.

2017-06-29 09:34 UTC, peppsac commented on src/Core/Scheduler/Providers/3dTiles_Provider.js
> +        if (urlSuffix.substring(0, 4) == 'http') {
I'd prefer : 
```js
if (urlSuffix.startsWith('http') {
    url = urlSuffix;
} else {
    url = metadata.urlPrefix + urlSuffix;
}
```

2017-06-29 09:34 UTC, peppsac commented on src/Core/Scheduler/Providers/3dTiles_Provider.js
> +        if (urlSuffix.substring(0, 4) == 'http') {
BTW, maybe you could rename `urlPrefix` -> `baseURL` and `urlSuffix` -> `url` or `path` ?

2017-06-29 09:34 UTC, peppsac commented on src/Renderer/ThreeExtended/PntsLoader.js
> +    points.RTC = geometry.RTC;
Same comment as above: return a ready to use object hierarchy instead.

2017-06-29 09:34 UTC, peppsac commented on src/Core/Scheduler/Providers/3dTiles_Provider.js
> +            result.scene.RTC = result.extensions.CESIUM_RTC.center;
I'd prefer the provider to directly implement RTC.
That could be done with something like:
```js
if (result.extensions.CESIUM_RTC) {
    group = new THREE.Group();
    group.position.fromArray(result.extensions.CESIUM_RTC.center); 
    group.children = scene.children;
    scene.children = [group];
}
```

2017-06-29 09:34 UTC, peppsac commented on src/Core/Scheduler/Providers/3dTiles_Provider.js
> +            result.scene.RTC = result.extensions.CESIUM_RTC.center;
Or maybe do this in the loader. This it'll work even when using the loader directly.

2017-06-29 09:50 UTC, NikoSaul commented on src/Core/Scheduler/Providers/3dTiles_Provider.js
> +        let url = metadata.urlPrefix + urlSuffix;
Yes because when i used lopocs, i had an absolute url. But yes, i forgot to add comment, my bad.

2017-07-03 07:46 UTC, peppsac reviewed
Thanks for the changes. 

Regardless of my review comments, you should probably rebase on PR #362 (which cleans up all examples, 3dtiles included).

2017-07-03 07:46 UTC, peppsac commented on src/Renderer/ThreeExtended/PntsLoader.js
> +        rtc.position.set(geometry.RTC[0], geometry.RTC[1], geometry.RTC[2]);
You can use `rtc.position.fromArray(geometry.RTC)`

2017-07-03 07:46 UTC, peppsac commented on src/Core/Scheduler/Providers/3dTiles_Provider.js
> +                            content.RTC.add(content);
Why don't you do this directly in the loaders?
Every user of .b3dm or .pnts will have to write the exact same code, so in my opinion it should be moved to the loader.

2017-07-03 08:41 UTC, autra commented on examples/3dtiles.html
> -
Is it possible to have it in another example html if this layer is removed from this example?

2017-07-03 09:37 UTC, NikoSaul commented on examples/3dtiles.html
> -
It's ok, i replaced my code of 3dtiles.html with yours, i used the same example. :)

2017-07-07 13:44 UTC, NikoSaul commented
@peppsac please r ? :)

2017-07-07 15:46 UTC, peppsac requested changes

2017-07-07 15:46 UTC, peppsac commented on src/Renderer/ThreeExtended/PntsLoader.js
> +        geometry.RTC = parseJSON.RTC_CENTER;
Is this necessary?

2017-07-07 15:46 UTC, peppsac commented on src/Renderer/ThreeExtended/B3dmLoader.js
> +                    gltf.scene.applyMatrix(matrix4_X);
The naming of the matrix is a bit strange.

Maybe `matrix4_X` could be renamed `matrixChangeUpVectorZtoY`  - it's a bit long, but it's clearer :)

2017-07-07 15:46 UTC, peppsac commented on src/Renderer/ThreeExtended/B3dmLoader.js
> +        gltf.position.set(json.extensions.CESIUM_RTC.center[0], json.extensions.CESIUM_RTC.center[1], json.extensions.CESIUM_RTC.center[2]);
`gltf.position.fromArray(json.extensions.CESIUM_RTC.center)` ?

2017-07-10 08:06 UTC, NikoSaul commented
@peppsac i hope it's ok now :+1:

2017-07-10 08:17 UTC, peppsac reviewed
Looks good (only left 2 small comments).

How can I test this?

2017-07-10 08:17 UTC, peppsac commented on src/Renderer/ThreeExtended/B3dmLoader.js
> +function parseInternalRTC(data, gltf) {
I'd suggest renaming this function to `applyOptionalCesiumRTC`.

2017-07-10 08:17 UTC, peppsac commented on src/Renderer/ThreeExtended/B3dmLoader.js
> +function parseInternalRTC(data, gltf) {
Each file type has its own RTC mechanism? `CESIUM_RTC` for `b3dm` and `RTC_CENTER` for `pnts`?

2017-07-10 08:17 UTC, peppsac commented on src/Core/Scheduler/Providers/3dTiles_Provider.js
> +        // For check if we have relative or absolute url (with tileset's lopocs for example)
Nit: remove `For`

2017-07-10 08:23 UTC, NikoSaul commented
Ok thank you i change that :) 
To test the RTC feature: go on the example 3dtiles.html and you should have 40 building (square) if you zoom on the dragon.

2017-07-10 08:24 UTC, NikoSaul commented on src/Renderer/ThreeExtended/B3dmLoader.js
> +function parseInternalRTC(data, gltf) {
Yes maybe, with this examples it's like that, so i suppose yes.

2017-07-10 09:57 UTC, peppsac approved these changes

2017-07-10 09:57 UTC, merged

2017-07-10 09:57 UTC, peppsac commented
Thanks :)