Updated readme for V2 release
iTowns/itowns pull request #395
Opened 2017-07-18 16:11 UTC by nosy-b

A few corrections for the release

2017-07-18 16:20 UTC, autra requested changes
Thanks! Just a few remarks, not much though.

2017-07-18 16:20 UTC, autra commented on README.md
> +iTowns has been redesigned from this [early version](https://github.com/iTowns/itowns-legacy)
missing `.` at the end.

2017-07-18 16:20 UTC, autra commented on README.md
> +It can connect to WMS/WMTS/TMS servers including elevation data and load many different data formats (3dTiles, gpx, KML and much much more).
Can you add a new line between line 8 and 9? I find it more readable

2017-07-18 16:20 UTC, autra commented on README.md
> +**[Demo](http://www.itowns-project.org/itowns2/examples/globe.html)**
You have the exact same link in the `examples` section just below. Maybe rename the `Examples` section to `Demo`?

2017-07-18 16:20 UTC, autra commented on README.md
> +**[Demo](http://www.itowns-project.org/itowns2/examples/globe.html)**
But it's nice to put doc link higher indeed!

2017-07-18 17:11 UTC, nosy-b commented
@autra Ok for the mods.
I agree as iTowns is not specifically a globe, I removed the Demo link. Examples will talk for themselves

2017-07-19 13:22 UTC, autra approved these changes

2017-07-19 13:22 UTC, autra commented
Thanks!

2017-07-19 13:22 UTC, merged