refactor: rework Tiles removal and cleanup
iTowns/itowns pull request #430
Opened 2017-08-01 12:32 UTC by peppsac

This commit removes TileMesh specific cleanup code and instead
introduce ObjectRemovalHelper that can be used on any object.

Another change is that attached layers get called on just-removed
elements. This allows each layer to perform its own cleanup.

2017-08-01 12:53 UTC, peppsac commented
I need to fix one last issue and update `TileDebug.js` as well before this is ready.

2017-08-01 13:12 UTC, peppsac commented
OK fixed.
You can test the difference by enabling the BoundingBox on the index.html sample and display the geometry count chart.

Then type:
```
globeView.controls.setRange(5000, true)
globeView.controls.setRange(25000000, true)
```
in the console and observe the variation in the geometry count chart.

Ideally, after going back at the initial position the geometry count should be the same as when itowns was started (= 90).

On master, this count never gets back to 90.
This PR fixes this problem.

2017-08-02 07:27 UTC, peppsac commented
@gchoqueux r?

2017-08-02 09:02 UTC, gchoqueux requested changes
OK 
just one comment

2017-08-02 09:02 UTC, gchoqueux commented on src/Process/ObjectRemovalHelper.js
> +     * @param {Boolean} callDispose Whether or not the initial obj should be disposed as well.
callDispose isn't used

2017-08-02 09:07 UTC, peppsac commented on src/Process/ObjectRemovalHelper.js
> +     * @param {Boolean} callDispose Whether or not the initial obj should be disposed as well.
Fixed!

2017-08-02 10:03 UTC, peppsac commented on src/Process/ObjectRemovalHelper.js
> +     * @param {Boolean} callDispose Whether or not the initial obj should be disposed as well.
For typo like this you can leave a comment but approve the PR.
This way I can fix it and merge directly without waiting for your approval.

2017-08-02 10:53 UTC, gchoqueux approved these changes

2017-08-02 11:05 UTC, merged