refacto: rework Camera's API
iTowns/itowns pull request #435
Opened 2017-08-02 14:35 UTC by peppsac

This commit changes the API of Camera as follow:
  - remove duplicate three.js-proxy function (like setRotation)
  - make this class GIS-aware: expose a function to retrieve the position in a
given crs
  - hide resize function and call it from update (since all the callers of resize
effectively call them in pair)

2017-08-03 15:44 UTC, gchoqueux requested changes

2017-08-03 15:44 UTC, gchoqueux commented on src/Renderer/Camera.js
> +    resize(this, width, height);
add test to update without resize (globe control example is broken )
```js
if (width && height) {
        resize(this, width, height);
}
```

2017-08-04 07:20 UTC, peppsac commented on src/Renderer/Camera.js
> +    resize(this, width, height);
I fixed all the callers of `camera.update()` instead.

2017-08-04 09:00 UTC, gchoqueux approved these changes

2017-08-04 09:00 UTC, merged