Local pointcloud globe
iTowns/itowns pull request #500
Opened 2017-09-29 16:04 UTC by ddespres

## Description
i would like to have an example of pointcloud data in a globe viewer but can't get it work

## Motivation and Context
This sample is not working at the moment and errors in the console are too nasty for me. So any help to get it work would be great and i think it could be another good sample to have.

## Screenshots (if appropriate)

2017-09-29 17:38 UTC, autra commented
> errors in the console are too nasty for me

Please post them here. 

You might want to create a GlobeView instead (to have the globe), then add your pointcloud to this view directly (see globe examples).

2017-10-03 19:08 UTC, ddespres commented
Thanks for your reply, that is what i've tried in the new sample i'm proposing.

I will try to post the errors tomorrow.


________________________________
De : Augustin Trancart <notifications@github.com>
Envoyé : vendredi 29 septembre 2017 19:38
À : iTowns/itowns
Cc : Damien DESPRES; Author
Objet : Re: [iTowns/itowns] Local pointcloud globe (#500)


errors in the console are too nasty for me

Please post them here.

You might want to create a GlobeView instead (to have the globe), then add your pointcloud to this view directly (see globe examples).

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/iTowns/itowns/pull/500#issuecomment-333190786>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AVe2HFvxqjcHYM6NNg-VCV8FUrYWODC9ks5snSsCgaJpZM4Po4fs>.

2017-10-04 09:48 UTC, ddespres commented
This is what i get in the console:
Uncaught TypeError: Cannot read property 'max' of undefined
    at at.Object.assign.intersectsBox (three.module.js:9023)
    at n.isBox3Visible (Camera.js:78)
    at a (PointCloudProcessing.js:119)
    at i.update (PointCloudProcessing.js:193)
    at a (MainLoop.js:43)
    at i._update (MainLoop.js:74)
    at i._step (MainLoop.js:99)
    at MainLoop.js:27

2017-11-06 10:47 UTC, peppsac commented
For now geometry reprojection is not supported - that may come later and #513 is a first step in this direction.

At the moment, to display a pointcloud on the globe the first requirement is: your pointcloud must use the `EPSG:4978` crs.

2017-11-24 11:15 UTC, gmaillet commented
A new version of this point cloud dataset in EPSG:4978 is now available on https://raw.githubusercontent.com/gmaillet/dataset/master/eglise_saint_blaise_arles.js (it will maybe have to be added on iTowns2-sample-data soon)
and the branch https://github.com/iTowns/itowns/tree/globePointCloud include a globe_pointcloud example that seems to work quite well

2017-11-24 11:46 UTC, ddespres commented
very nice! thanks

2017-11-30 14:13 UTC, nosy-b commented
@gmaillet @peppsac Super cool!

(But it's another example where the GlobeControl is annoying: When clicking on something else than the globe (here , pointclouds) you can't move the camera anymore. You have to play with globeView.mainLoop.gfxEngine.getUniqueThreejsLayer() like everytime you put something on the globe. 
It should be the opposite: By default you interact only (with the depthtest) with the globe with a Globe controller)

2017-12-08 15:46 UTC, gliegard requested changes
You need to rebase your branch on the master of this repo.
Here is how to do it
```
git remote add upstream https://github.com/itowns/itowns.git
git fetch upstream
git rebase upstream/master
```

See also my comments below.

And then use `npm test` to see lint error in the example.

2017-12-08 15:46 UTC, gliegard commented on examples/pointcloud_globe.html
> +             <input id="url" type="url" value="https://raw.githubusercontent.com/iTowns/iTowns2-sample-data/master/pointclouds/eglise_saint_blaise_arles/eglise_saint_blaise_arles.js">
As @gmaillet told you, you must use these new sources
https://raw.githubusercontent.com/gmaillet/dataset/master/eglise_saint_blaise_arles.js

2017-12-08 15:46 UTC, gliegard commented on examples/pointcloud_globe.js
> +    var positionOnGlobe = { longitude: 2.351323, latitude: 48.856712, altitude: 25000000 };
You can use Arles precise coordinates
`var positionOnGlobe = { longitude: 4.631512, latitude: 43.675626, altitude: 250 };`

2017-12-08 15:46 UTC, gliegard commented on examples/pointcloud_globe.js
> +    function onLayerReady() {
Here you can drop the code that places the camera (from line 70 to 78) because we don't need to change camera settings in globe view.

2017-12-08 15:46 UTC, gliegard commented on examples/pointcloud_globe.js
> +    promises.push(itowns.Fetcher.json('./layers/JSONLayers/OPENSM.json').then(addLayerCb));
You can add an elevation layer :
`promises.push(itowns.Fetcher.json('./layers/JSONLayers/IGN_MNT_HIGHRES.json').then(addLayerCb));`

2017-12-08 15:46 UTC, gliegard commented on examples/pointcloud_globe.js
> +    view.addLayer(pointcloud);//.then(onLayerReady);
Here is the solution for your exception, it's a bit ugly but we need to explicitly call the good addLayer function,
we'll fix that later, but for now, try this line
`itowns.View.prototype.addLayer.call(view, pointcloud).then(onLayerReady);`

2018-01-18 16:28 UTC, gliegard commented
@ddespres Can you finalize you PR with theses changes ?

If you don't have the time, i can do it in another PR next week.

2018-01-22 09:02 UTC, ddespres commented
@gliegard sorry, i'm no more working on the subject for the moment and won't have time this week to get back into the subject

2018-01-22 14:52 UTC, gliegard commented
Ok, no problem, thanks for the PR :)

I close this PR, I did another equivalent PR here #620

2018-01-22 14:52 UTC, closed without merging