Add panorama display capabilities
iTowns/itowns pull request #560
Opened 2017-10-27 14:52 UTC by peppsac

This PR adds all the needed code to display panoramas.
Panoramas can use either:
  - an equirectangular projection: in which case they're drawn using a sphere
  - a cylindrical projection: drawn on a cylinder

The underlying geometry is tiled which allows to display high resolution panoramas,
for instance using the StaticProvider.

The 2nd commit adds an example using the feature.

Note: this PR depends on PRs #556 #555 #554 and #559

2017-11-13 13:57 UTC, peppsac commented
Rebased and ready to review.

2017-11-16 07:55 UTC, zarov commented
It doesn't seem to work for me in Firefox (57, Ubuntu), unless I load the tab without having the focus on it (right-click on non focused-tab, "refresh tab"). Does anyone else have the same problem ?

Another thing that bothers me is the fact that tiles take some time to reload again, when displayed again. I understand that it is the same functioning as for a map, but for a mid resolution panorama such as your examples, it is kinda a pity to see this transition. Is it possible to specify a case for low/mid res panorama, where this doesn't happen ?
But keep in mind that for (very) high resolution panorama, I agree that the original solution is a good solution.

And lastly, concerning cube projection, is it planned to be added ?

2017-11-16 08:26 UTC, peppsac commented
> It doesn't seem to work for me in Firefox (57, Ubuntu), unless I load the tab without having the focus on it (right-click on non focused-tab, "refresh tab"). Does anyone else have the same problem ?

I just rebased on master and it haved fixed your problem (thanks to #574 ). Can you test again?

> Another thing that bothers me is the fact that tiles take some time to reload again, when displayed again

Not sure what you mean here?

> Is it possible to specify a case for low/mid res panorama, where this doesn't happen ?

It's already possible to use a single image, this way you wouldn't have any transition.
Also if you (or anyone) can share some really high resolution panorama I would happily use them for the example.

> And lastly, concerning cube projection, is it planned to be added ?

Not yet.

2017-11-16 09:08 UTC, zarov commented
It works fine, thanks ! And nvm the second comment, all solved now too.

Unfortunately, a lot of high res panorama are partial, not full spherical, and also not free to use. I'm having a look into it, if I can find some.

2017-11-16 09:44 UTC, zarov commented
Found one ! There is this [Prague 34Gigapixels](http://360gigapixels.com/petrin-prague-photo/) that's available in CC BY-NC-SA, that can be downloaded [here (last link in the list)](http://www.jeffrey-martin.com/#gigapixel-photography). 

You can also get full equirectangular (you'll have to tile it) by doing a research similar to this https://www.google.fr/search?q=equirectangular&tbs=isz:lt,islt:70mp,sur:fmc&tbm=isch&source=lnt

2017-11-16 11:05 UTC, zarov requested changes
Seems quite good to me, needs some changes though.

2017-11-16 11:05 UTC, zarov commented on src/Core/Prefab/Panorama/PanoramaTileBuilder.js
> +PanoramaTileBuilder.prototype.Center = function Center(params) {
Maybe invert `Center` and `Prepare` for coherence with other builders.

2017-11-16 11:05 UTC, zarov commented on src/Core/Prefab/Panorama/PanoramaTileBuilder.js
> +PanoramaTileBuilder.prototype.uProjecte = function uProjecte(u, params) {
Same here, `uProjecte` and `vProjecte` should come after `VertexPosition` and `VertexNormal`.

2017-11-16 11:05 UTC, zarov commented on src/Core/Prefab/Panorama/PanoramaTileBuilder.js
> +        this.equirectangular = true;
Couldn't we change this to an enum, if we want to add cube support later ?

2017-11-16 11:05 UTC, zarov commented on src/Core/Prefab/PanoramaView.js
> +    this.scene.add(tileLayer.object3d);
Not necessary, it's added later in `View#addLayer`.

2017-11-16 11:05 UTC, zarov commented on src/Core/Prefab/PanoramaView.js
> +    View.prototype.addLayer.call(this, tileLayer);
Why not `this.addLayer` instead ?

2017-11-16 15:57 UTC, peppsac commented
> Got one ! There is this Prague 34Gigapixels that's available in CC BY-NC-SA, that can be downloaded here (last link in the list).

Unfortunately you can only download the preprocessed files (split in small tiles) so I can't use it.

Note that I ran my preprocess app again with different settings and the quality should be better now.

2017-11-16 15:59 UTC, peppsac commented on src/Core/Prefab/PanoramaView.js
> +    View.prototype.addLayer.call(this, tileLayer);
Because `PanoramView.addLayer` is overriden currently, and is meant to be used with 'color' layers.

2017-11-16 15:59 UTC, peppsac commented on src/Core/Prefab/PanoramaView.js
> +    this.scene.add(tileLayer.object3d);
Correct, fixed.

2017-11-16 16:02 UTC, peppsac commented on src/Core/Prefab/Panorama/PanoramaTileBuilder.js
> +PanoramaTileBuilder.prototype.Center = function Center(params) {
I changed the order of the functions.

2017-11-17 09:43 UTC, zarov commented
Changes are good to me.
Quality is quite good now ! Thanks for that improvement.

2017-11-17 09:43 UTC, zarov approved these changes

2017-11-20 10:24 UTC, merged

2017-11-20 16:21 UTC, nosy-b commented
Thanks @peppsac, very cool new feature!

I'm a bit late but a few remarks:
- When creating a new example (panorama.html), please add some comments in it
- It should appear in the examples/index.html
- Why do you refine the geometry (that much)? It creates too much triangles