fix: use babel-polyfill and url-polyfill to support IE11
iTowns/itowns pull request #569
Opened 2017-11-10 16:28 UTC by peppsac

This change increases itowns.js bundle size by ~100KB.

Fixes #510

2017-11-10 17:05 UTC, tbroyer submitted a review, later dismissed
> This change increases itowns.js bundle size by ~100KB.

fwiw, I believe that was the reason for not using it initially.

Should we build 2 bundles depending on browser support? (i.e. whether one wants to support IE11 –and earlier?– or not)

Or choose other, smaller, polyfills? E.g. `es6-promise/auto` and [`String.prototype.includes`](https://github.com/mathiasbynens/String.prototype.includes)

2017-11-10 17:05 UTC, tbroyer commented on package.json
>      "es6-promise": "^4.0.5",
This needs to be removed then.

2017-11-10 17:25 UTC, autra commented
> fwiw, I believe that was the reason for not using it initially.

Are you thinking about https://github.com/iTowns/itowns/pull/417 or another discussion?

2017-11-14 10:59 UTC, peppsac commented
@gcebelieu since you reported https://github.com/iTowns/itowns/issues/510, could you confirm that this PR works for you?

@tbroyer I've removed es6-promise.

2017-11-14 11:21 UTC, gcebelieu commented
Thanks @peppsac, I will have access to a windows with ie11 machine only tomorrow. I'll test then and tell you.

2017-11-15 08:43 UTC, gcebelieu commented
@peppsac I couldn't find a working example on ie11. For instance, index.html or globe.html examples are now blocking on this error : 

> "dat" est indéfini

in this piece of code (line 9) from GuiTools.js

```
dat.GUI.prototype.removeFolder = function removeFolder(name) {
    var folder = this.__folders[name];
    if (!folder) {
        return;
    }
    folder.close();
    this.__ul.removeChild(folder.domElement.parentNode);
    delete this.__folders[name];
    this.onResize();
};
```

Maybe a side effet, not really linked to this PR, but is there an example that doesn't involves gui stuff ? On which example did you make your ie tests ?

2017-11-15 11:20 UTC, autra requested changes
Things are not perfect for the globe but it's already a *lot* better (other issues look like webgl ones). Other examples are working good. You just need to amend your commit messages ("fix(compat)" maybe?). Also imho you can squash these 2 commits because babel-polyfill replaces es6-promise.

@gcebelieu weird. Maybe dat.gui hasn't been downloaded by your browser? Can you check the `network` tab of your devtools? That being said, we do have some examples without this js: planar.html, multiglobe.html and a bunch of others (split, planar kml, globe gpx, the cube example... check the html in `examples/`)

2017-11-15 14:54 UTC, autra approved these changes

2017-11-15 14:55 UTC, autra commented
@gcebelieu I believe your issue is not linked to this PR. Can you retest with one of the example not including dat.gui please?

2017-11-15 17:06 UTC, gcebelieu commented
I have other errors with examples non involving dat.gui but this may comes from my environment (I'm not very familiar with windows).
As Promise errors disappeared, I'm OK with that PR.

2017-11-15 18:25 UTC, autra commented
Okay, let's merge that. @gcebelieu please don't hesitate to open issues if you still have errors. You can directly test on http://www.itowns-project.org/itowns/examples/index.html, this'll remove some environment issues hopefully.

2017-11-15 18:25 UTC, merged