fix(loader): remove two warnings
iTowns/itowns pull request #587
Opened 2017-11-17 14:16 UTC by gliegard

## Description
Remove warning from GLTFLoader

Prior to this change, we can see these warnings
WARNING in ./src/Renderer/ThreeExtended/B3dmLoader.js
12:26-42 "export 'GLTFLoader' (imported as 'THREE') was not found in 'three'
WARNING in ./src/Renderer/ThreeExtended/GLTFLoader.js
18:0-16 "export 'GLTFLoader' (imported as 'THREE') was not found in 'three'

2017-11-17 14:28 UTC, autra requested changes
It removes warnings, but break itowns :-O

2017-11-17 14:28 UTC, autra commented on src/Renderer/ThreeExtended/GLTFLoader.js
> +GLTFLoader = ( function () {
You need to export it. `export default (function() {...}` would be enough I guess

2017-11-17 14:31 UTC, autra commented
To be more precise, the error is `ReferenceError: assignment to undeclared variable GLTFLoader`, because the outer GLTFLoader var is not defined in this scope, directly exposing the result of calling the outer function will get rid of it (not tested though).

2017-11-20 10:25 UTC, gliegard commented
tanks for the precisions :)
I've updated the code !

2017-11-20 11:14 UTC, autra approved these changes
Perfect, thanks for this clean!

2017-11-20 11:15 UTC, merged