feat(core): add a 'radius' parameter to picking methods
iTowns/itowns pull request #755
Opened 2018-05-16 16:04 UTC by peppsac

This radius parameter allows to be more tolerant towards user input.

Especially when working wiht point cloud, it's tedious to require the
user to exactly hover a point with the mouse.

BREAKING CHANGE: this modifies the signature of all picking functions.

2018-05-17 07:53 UTC, zarov requested changes
While this is really nice to have, it is really reducing the performance (at least in my case), even if it is to be expected, as more things are verified. See the two chrome profiles here: 
https://framadrop.org/r/V-k-XsRgOk#PMpo6NrV60XOooZxPx4F9Ia+mH7wbainhC5xgOs+8Lw=
https://framadrop.org/r/yRsZqCVNNr#c7v2a3DpLpAMA6QgT+sVaKHZUISrsevYzcQOB4SySfM=

2018-05-17 07:53 UTC, zarov commented on src/Core/Picking.js
> +    pickTilesAt: (_view, mouse, radius, layer) => {
Could you add a quick documentation at least, so we aren't lost later ? (even if this isn't an exposed API and no documentation is generated from it)

2018-05-17 07:53 UTC, zarov commented on test/examples/wfs.js
> +        const buildingId = await page.evaluate(() => picking({ x: 342, y: 243 }).properties.id);
This could be in another test, to be on the same page as other examples.

2018-05-17 07:53 UTC, zarov commented on src/Core/Picking.js
> +    for (let r = 0; r <= radius; r++) {
You can have instead:
```js
let prevSq = 0;
for (let r = 1; r <= radius; r++)
```

2018-05-17 07:58 UTC, peppsac commented on src/Core/Picking.js
> +    for (let r = 0; r <= radius; r++) {
That would miss the central point.

2018-05-17 07:59 UTC, zarov commented on src/Core/Picking.js
> +    for (let r = 0; r <= radius; r++) {
Yep my bad

2018-05-17 14:21 UTC, peppsac commented
@zarov can you retest now? Performance should be better. I also added a bit of documentation for the Picking module.

2018-05-22 08:15 UTC, zarov approved these changes
Way better, thanks ! This seems good to me.

2018-05-29 12:53 UTC, merged

2018-05-29 13:58 UTC, zarov commented
@peppsac please don't forget to squash when merging PR like this one.

2018-05-29 13:59 UTC, peppsac commented
@zarov arg, sorry !