docs(3dtiles): add 3dtiles layer documentation
iTowns/itowns pull request #802
Opened 2018-07-10 13:03 UTC by peppsac

This is a proposal to document the type of layers and their protocol specific options.

I think it would work well for all *Provider files.

WDYT?

2018-07-10 13:13 UTC, autra commented on src/Provider/3dTilesProvider.js
> + * layer.url = 'http://example/tileset.json;
:-O

2018-07-10 13:26 UTC, peppsac commented
I also simplified the 3dtiles usage by defining sane default value for layer.

Now creating a 3dtiles layer only requires to define the `url` and the `protocol`.

2018-07-19 12:43 UTC, peppsac commented
Rebased to remove the commit merged in #811.

2018-07-19 12:46 UTC, peppsac commented
Here's the result in the documentation side-bar:

![capture d ecran de 2018-07-19 14-44-30](https://user-images.githubusercontent.com/2198295/42943146-460b1f8a-8b62-11e8-9f4a-cb80462ef1ca.png)

I think @autra has concern about using `@module` for something that's not really a module so I'd be happy to hear (and see!) other proposals.

The objective here is to provide an easy to find documentation for each protocol-specific options.

2018-07-19 12:55 UTC, gchoqueux requested changes

2018-07-19 12:55 UTC, gchoqueux commented on src/Provider/3dTilesProvider.js
> + * @module 3d-tiles
* What is the structure of instanced objects for 3dTiles (THREE.js and itowns) and not the specification. 

for example in node tile :

```js
tileA  // (THREE.Mesh->itowns.tileMesh)
     {
          children: [tileB, tileC] // (Array) tile children
          parent: tile0  // (THREE.Mesh->itowns.tileMesh) tile parent 
          obb: // (itowns.OBB)  oriented bouding box
     }
```
in `3dTiles`, how are the objects linked: `content, parent, bounding Volume, region, transform ...`

2018-07-19 12:55 UTC, gchoqueux commented on src/Provider/3dTilesProvider.js
> + * layer.url = 'http://example/tileset.json';
add `layer.type = 'geometry';`

2018-07-19 12:55 UTC, gchoqueux commented on src/Provider/3dTilesProvider.js
> + * @property {number} [sseThreshold=16] - s(creen) s(pace) e(rror) threshold in pixels.
would you add which sse method is used?

2018-07-19 12:55 UTC, gchoqueux commented on src/Provider/3dTilesProvider.js
> + * @property {number} [cleanupDelay=1000] - delay in milliseconds after which an
there's also not a random draw for node deletion?

2018-07-20 09:54 UTC, zarov commented
I'll join @autra here. This may be better to not document each protocol using jsdoc, but maybe in a markdown file, and include it during the generation of the documentation, like we include the readme in the first page. Thus we could have a section in the menu like `Protocols`.

2018-07-20 10:58 UTC, mbredif commented
I think that is a sign that our protocol implementation is odd : with static functions modifying an external layer object  instead of constructing an object (a source?).

2018-07-23 08:40 UTC, peppsac commented
> This may be better to not document each protocol using jsdoc, but maybe in a markdown file, and include it during the generation of the documentation, like we include the readme in the first page.

I agree with this. But until then happens, the protocols options aren't documented.

> I think that is a sign that our protocol implementation is odd : with static functions modifying an external layer object instead of constructing an object (a source?).

Nope. That's only a sign that `jsdoc` can only handle class/object based API.


Anyway closing this PR, since the consensus seems to indicate that this is not the correct way to do it.

2018-07-23 08:40 UTC, closed without merging

2018-08-30 09:14 UTC, jailln commented
Too bad that this job was left over; as a user it would have been great to have documentation on the layers :)