chore(features): remove unused minAltitude property
iTowns/itowns pull request #817
Opened 2018-07-24 12:06 UTC by zarov

The minAltitude property when creating a Mesh from a Feature was not
assigned and always equal to a NaN, so it has been removed.

Not sure if we could remove it from FeatureProcessing too.

2018-07-24 12:46 UTC, gchoqueux commented
Should be fixed, i was removed in pr #691 [here ](https://github.com/iTowns/itowns/pull/691/files#diff-2a78502be7a11a150dcce98113215193L211)

2018-07-24 12:49 UTC, peppsac commented
> Should be fixed, i was removed in pr #691 here 

This PR was merged 3 months ago, and no one complained about this `minAltitude` thing being broken.

So instead of assessing "should be fixed" in a rather unhelpful way, you should explain why it should be "fixed" (I assume you meant restored?).

2018-07-24 13:23 UTC, zarov commented
> in a rather unhelpful way

Your comment is not helpful either, a simple "could you explain more on the issue ?" would have been enough. But let's not change the subject here.

The problem with the removal of `minAltitude` is kind of hidden. If you load the `globe_wfs_extruded` example, and select a wireframe view before the apparition of the WFS layer, you can see that buildings are not extruding from their real altitude but rather from "far" below the ground. The `minAltitude` parameter was introduced to prevent this problem in the past. So I need to either add it back or find a replacement to it.

2018-07-24 13:29 UTC, peppsac commented
> Your comment is not helpful either, a simple "could you explain more on the issue ?" would have been enough.

Noted.

2018-08-02 08:50 UTC, gchoqueux requested changes
doesn't remove minAltitude, it is needed to position features. on the other hand, it is necessary to fix the calculation that was deleted

2018-10-12 13:30 UTC, gchoqueux commented
fix in #870

2018-10-12 13:30 UTC, closed without merging