feat(converter): add batchId attribute in mesh from convert of feature2Mesh
iTowns/itowns pull request #992
Opened 2019-01-11 15:08 UTC by gchoqueux

Resumption of the work of @mbredif in #909

## Description
adds a `batchId`  attribute in `mesh.material` that creates a `batchId` attribute to be consumed by shaders.

## Motivation and Context
restore the functionnality. may be used for  feature selection, selective shading with the selected `batchId` passed as a uniform...

2019-01-17 10:01 UTC, zarov requested changes
Implementation is good, however I sense a lot of duplicate things: could you mutualize somehow in an external method this part:
```js
 if (batchIds) {
     const id = options.batchId(geometry.properties, featureId);
     for (let i = start; i < end; i++) {
         batchIds[i] = id;
     }
     featureId++;
 }
```

2019-01-17 10:01 UTC, zarov commented on src/Converter/Feature2Mesh.js
> +     * @param {function} [options.batchId] - optional function to create batchId attribute. It is passed the feature property and the feature index
Could you give an example of use of the generated batchId ?

2019-01-17 10:01 UTC, zarov commented on src/Converter/Feature2Mesh.js
> +    if (batchIds) { geom.addAttribute('batchId', new THREE.BufferAttribute(batchIds, 1)); }
What is the point of adding them as an attribute ? AFAIK it is not used in a shader, so it could be stored in an array.

2019-01-17 10:01 UTC, zarov commented on src/Converter/Feature2Mesh.js
> +    const batchIds = options.batchId ?  new Uint32Array(vertices.length / 3) : undefined;
If we only allow `uint32` to be generated, it needs to be specified in the documentation.

2019-01-28 17:01 UTC, gchoqueux commented on src/Converter/Feature2Mesh.js
> +     * @param {function} [options.batchId] - optional function to create batchId attribute. It is passed the feature property and the feature index
I added a example to pick building in wfs example. In another PR, I'll add a example to use `batchId` attribute with shader material.

2019-01-28 17:01 UTC, gchoqueux commented on src/Converter/Feature2Mesh.js
> +    if (batchIds) { geom.addAttribute('batchId', new THREE.BufferAttribute(batchIds, 1)); }
see my [comment](https://github.com/iTowns/itowns/pull/992#discussion_r251505124)

2019-01-29 07:45 UTC, zarov approved these changes
All good, please correct the french typo before merging

2019-01-29 07:45 UTC, zarov commented on src/Converter/Feature2Mesh.js
> +     * @param {function} [options.batchId] - optional function to create batchId attribute. It is passed the feature property and the feature index. As the batchId is using an unsigned int structure
"le batchId" -> "the batchId"

2019-01-29 09:46 UTC, gchoqueux commented on src/Converter/Feature2Mesh.js
> +    const batchIds = options.batchId ?  new Uint32Array(vertices.length / 3) : undefined;
added

2019-01-29 09:47 UTC, gchoqueux commented on src/Converter/Feature2Mesh.js
> +     * @param {function} [options.batchId] - optional function to create batchId attribute. It is passed the feature property and the feature index. As the batchId is using an unsigned int structure
changed

2019-01-29 10:30 UTC, merged